apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Dynamic preview overlay - lightweight, no LB, uses nginx ingress
namespace: webapp-team

resources:
- ../../base
- ingress-nginx.yaml

# Patch service to use ClusterIP for internal-only access
patches:
- target:
    kind: Service
    name: webapp-service
  patch: |-
    - op: replace
      path: /spec/type
      value: ClusterIP

# Labels for preview environments
labels:
- pairs:
    team: webapp-team
    tier: preview
  includeSelectors: false