# Certificate resources for preview environments
---
# Google-managed certificate for the preview domain
apiVersion: certificatemanager.cnrm.cloud.google.com/v1beta1
kind: CertificateManagerCertificate
metadata:
  name: webapp-cert # from-param: ${CERT_NAME}
  namespace: ${NAMESPACE} # from-param: ${NAMESPACE}
  annotations:
    cnrm.cloud.google.com/project-id: u2i-tenant-webapp-nonprod
spec:
  projectRef:
    external: u2i-tenant-webapp-nonprod
  location: global
  description: Certificate for webapp # from-param: ${CERT_DESCRIPTION}
  managed:
    domains:
    - example.com # from-param: ${DOMAIN}

---
# Certificate map entry to associate certificate with the map
apiVersion: certificatemanager.cnrm.cloud.google.com/v1beta1
kind: CertificateManagerCertificateMapEntry  
metadata:
  name: webapp-entry # from-param: ${CERT_ENTRY_NAME}
  namespace: ${NAMESPACE} # from-param: ${NAMESPACE}
  annotations:
    cnrm.cloud.google.com/project-id: u2i-tenant-webapp-nonprod
spec:
  projectRef:
    external: u2i-tenant-webapp-nonprod
  mapRef:
    name: webapp-cert-map
    namespace: infra-gw
  certificatesRefs:
  - name: webapp-cert # from-param: ${CERT_NAME}
  hostname: example.com # from-param: ${DOMAIN}