apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# KCC resources for preview environment
# These are deployed with statusCheck disabled to avoid Skaffold bug #7207

resources:
# Use base certificate template with parameters
- ../../../base/certificate-template.yaml

# Common labels for all KCC resources
commonLabels:
  app.kubernetes.io/component: webapp