# Config Connector Backend Service with Autoneg annotation
# This automatically discovers and attaches NEGs created by the service

apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeBackendService
metadata:
  name: webapp-dev-backend
  annotations:
    cnrm.cloud.google.com/project-id: u2i-tenant-webapp
    # Autoneg annotation - automatically attaches NEGs matching this service
    cloud.google.com/neg-status: |
      {
        "network_endpoint_groups": {
          "80": "webapp-neg"
        },
        "zones": ["europe-west1-b", "europe-west1-c", "europe-west1-d"]
      }
spec:
  protocol: TCP
  loadBalancingScheme: EXTERNAL
  healthChecks:
  - healthCheckRef:
      name: webapp-dev-health
  connectionDrainingTimeoutSec: 60
  portName: http
  timeoutSec: 30