# Strategic merge patches to fix Certificate Manager resources
# Removes labels that contain dots which are not allowed by Certificate Manager API

apiVersion: certificatemanager.cnrm.cloud.google.com/v1beta1
kind: CertificateManagerCertificate
metadata:
  name: webapp-dev-cert
  labels:
    environment: non-prod
    managed-by: config-connector
    $patch: replace
---
apiVersion: certificatemanager.cnrm.cloud.google.com/v1beta1
kind: CertificateManagerDNSAuthorization
metadata:
  name: webapp-dev-auth
  labels:
    environment: non-prod
    managed-by: config-connector
    $patch: replace
---
apiVersion: certificatemanager.cnrm.cloud.google.com/v1beta1
kind: CertificateManagerCertificateMap
metadata:
  name: webapp-cert-map
  labels:
    environment: non-prod
    managed-by: config-connector
    $patch: replace
---
apiVersion: certificatemanager.cnrm.cloud.google.com/v1beta1
kind: CertificateManagerCertificateMapEntry
metadata:
  name: webapp-dev-entry
  labels:
    environment: non-prod
    managed-by: config-connector
    $patch: replace