# Config Connector resources for non-prod
# These create the L4 TCP proxy load balancer with TLS termination

# Reserve static IP address
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeAddress
metadata:
  name: webapp-dev-ip
  annotations:
    cnrm.cloud.google.com/project-id: u2i-tenant-webapp
spec:
  location: global
  addressType: EXTERNAL
  description: "Static IP for webapp dev environment"
---
# Certificate Manager - Modern approach for SSL certificates with full GitOps control
# 1. Google-managed certificate
apiVersion: certificatemanager.cnrm.cloud.google.com/v1beta1
kind: CertificateManagerCertificate
metadata:
  name: webapp-dev-cert
  annotations:
    cnrm.cloud.google.com/project-id: u2i-tenant-webapp
  labels:
    environment: non-prod
    managed-by: config-connector
spec:
  projectRef:
    external: u2i-tenant-webapp
  location: global
  managed:
    domains:
    - dev.webapp.u2i.dev
    dnsAuthorizationsRefs:
    - name: webapp-dev-auth
---
# 2. DNS-01 authorization for the domain
apiVersion: certificatemanager.cnrm.cloud.google.com/v1beta1
kind: CertificateManagerDNSAuthorization
metadata:
  name: webapp-dev-auth
  annotations:
    cnrm.cloud.google.com/project-id: u2i-tenant-webapp
  labels:
    environment: non-prod
    managed-by: config-connector
spec:
  projectRef:
    external: u2i-tenant-webapp
  domain: dev.webapp.u2i.dev
---
# 3. Certificate map to group certificates
apiVersion: certificatemanager.cnrm.cloud.google.com/v1beta1
kind: CertificateManagerCertificateMap
metadata:
  name: webapp-cert-map
  annotations:
    cnrm.cloud.google.com/project-id: u2i-tenant-webapp
  labels:
    environment: non-prod
    managed-by: config-connector
spec:
  projectRef:
    external: u2i-tenant-webapp
---
# 4. Map entry to bind hostname to certificate
apiVersion: certificatemanager.cnrm.cloud.google.com/v1beta1
kind: CertificateManagerCertificateMapEntry
metadata:
  name: webapp-dev-entry
  annotations:
    cnrm.cloud.google.com/project-id: u2i-tenant-webapp
  labels:
    environment: non-prod
    managed-by: config-connector
spec:
  projectRef:
    external: u2i-tenant-webapp
  mapRef:
    name: webapp-cert-map
  certificatesRefs:
  - name: webapp-dev-cert
  hostname: dev.webapp.u2i.dev
---
# Health Check
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeHealthCheck
metadata:
  name: webapp-dev-health
  annotations:
    cnrm.cloud.google.com/project-id: u2i-tenant-webapp
spec:
  location: global
  checkIntervalSec: 10
  timeoutSec: 5
  healthyThreshold: 2
  unhealthyThreshold: 3
  tcpHealthCheck:
    port: 8080
---
# Backend Service
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeBackendService
metadata:
  name: webapp-dev-backend
  annotations:
    cnrm.cloud.google.com/project-id: u2i-tenant-webapp
spec:
  location: global
  protocol: TCP
  loadBalancingScheme: EXTERNAL
  healthChecks:
  - healthCheckRef:
      name: webapp-dev-health
  connectionDrainingTimeoutSec: 60
  # NEG attachment requires autoneg controller or manual attachment
  # The service annotation anthos.cft.dev/autoneg would handle this automatically
---
# SSL Policy
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeSSLPolicy
metadata:
  name: webapp-ssl-policy
  annotations:
    cnrm.cloud.google.com/project-id: u2i-tenant-webapp
spec:
  profile: MODERN
  minTlsVersion: TLS_1_2
---
# Target SSL Proxy
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeTargetSSLProxy
metadata:
  name: webapp-dev-ssl-proxy
  annotations:
    cnrm.cloud.google.com/project-id: u2i-tenant-webapp
spec:
  backendServiceRef:
    name: webapp-dev-backend
  certificateMapRef:
    external: //certificatemanager.googleapis.com/projects/u2i-tenant-webapp/locations/global/certificateMaps/webapp-cert-map
  sslPolicyRef:
    name: webapp-ssl-policy
  proxyHeader: NONE
---
# Forwarding Rule
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeForwardingRule
metadata:
  name: webapp-dev-forwarding
  annotations:
    cnrm.cloud.google.com/project-id: u2i-tenant-webapp
spec:
  location: global
  portRange: "443"
  ipProtocol: TCP
  loadBalancingScheme: EXTERNAL
  target:
    targetSSLProxyRef:
      name: webapp-dev-ssl-proxy
  ipAddress:
    addressRef:
      name: webapp-dev-ip
