# Config Connector resources for non-prod
# These create resources for the L7 HTTPS load balancer

# Reserve static IP address
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeAddress
metadata:
  name: webapp-dev-ip
  annotations:
    cnrm.cloud.google.com/project-id: u2i-tenant-webapp
spec:
  location: global
  addressType: EXTERNAL
  description: "Static IP for webapp dev environment"
---
# Certificate Manager - Managed certificate with DNS challenge
apiVersion: certificatemanager.cnrm.cloud.google.com/v1beta1
kind: CertificateManagerCertificate
metadata:
  name: webapp-cert
  annotations:
    cnrm.cloud.google.com/project-id: u2i-tenant-webapp
spec:
  projectRef:
    external: u2i-tenant-webapp
  location: global
  managed:
    domains:
    - dev.webapp.u2i.dev
    dnsAuthorizationsRefs:
    - name: webapp-auth
---
# DNS Authorization for certificate
apiVersion: certificatemanager.cnrm.cloud.google.com/v1beta1
kind: CertificateManagerDNSAuthorization
metadata:
  name: webapp-auth
  annotations:
    cnrm.cloud.google.com/project-id: u2i-tenant-webapp
spec:
  projectRef:
    external: u2i-tenant-webapp
  domain: dev.webapp.u2i.dev
---
# Certificate Map
apiVersion: certificatemanager.cnrm.cloud.google.com/v1beta1
kind: CertificateManagerCertificateMap
metadata:
  name: webapp-cert-map
  annotations:
    cnrm.cloud.google.com/project-id: u2i-tenant-webapp
spec:
  projectRef:
    external: u2i-tenant-webapp
---
# Certificate Map Entry
apiVersion: certificatemanager.cnrm.cloud.google.com/v1beta1
kind: CertificateManagerCertificateMapEntry
metadata:
  name: webapp-entry
  annotations:
    cnrm.cloud.google.com/project-id: u2i-tenant-webapp
spec:
  projectRef:
    external: u2i-tenant-webapp
  mapRef:
    name: webapp-cert-map
  hostname: dev.webapp.u2i.dev
  certificatesRefs:
  - name: webapp-cert
---
# Ingress for L7 HTTPS Load Balancer
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webapp-ingress
  annotations:
    kubernetes.io/ingress.class: gce
    kubernetes.io/ingress.global-static-ip-name: webapp-dev-ip
    ingress.gcp.kubernetes.io/pre-shared-cert: webapp-cert-map
    external-dns.alpha.kubernetes.io/hostname: dev.webapp.u2i.dev
    external-dns.alpha.kubernetes.io/ttl: "300"
spec:
  rules:
  - host: dev.webapp.u2i.dev
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: webapp-service
            port:
              number: 80
