# Config Connector resources for non-prod
# These create the L4 TCP proxy load balancer with TLS termination

# Reserve static IP address
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeAddress
metadata:
  name: webapp-dev-ip
  annotations:
    cnrm.cloud.google.com/project-id: u2i-tenant-webapp
spec:
  location: global
  addressType: EXTERNAL
  description: "Static IP for webapp dev environment"
---
# Service with NEG annotation for automatic endpoint management (L7)
apiVersion: v1
kind: Service  
metadata:
  name: webapp-service-neg
  annotations:
    cloud.google.com/neg: '{"exposed_ports":{"80":{"name":"webapp-neg-80"}}}'
    external-dns.alpha.kubernetes.io/hostname: dev.webapp.u2i.dev
    external-dns.alpha.kubernetes.io/ttl: "300"
spec:
  type: ClusterIP
  selector:
    app: webapp
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
---
# Health Check for HTTP
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeHealthCheck
metadata:
  name: webapp-http-hc
  annotations:
    cnrm.cloud.google.com/project-id: u2i-tenant-webapp
spec:
  location: global
  checkIntervalSec: 10
  timeoutSec: 5
  healthyThreshold: 2
  unhealthyThreshold: 3
  httpHealthCheck:
    port: 80
    requestPath: /
---
# Backend Service for L7 HTTP load balancing
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeBackendService
metadata:
  name: webapp-l7-backend
  annotations:
    cnrm.cloud.google.com/project-id: u2i-tenant-webapp
spec:
  location: global
  protocol: HTTP
  loadBalancingScheme: EXTERNAL_MANAGED
  healthChecks:
  - healthCheckRef:
      name: webapp-http-hc
  connectionDrainingTimeoutSec: 30
  backend:
  - balancingMode: RATE
    maxRatePerEndpoint: 100
    group:
      networkEndpointGroupRef:
        external: projects/u2i-tenant-webapp/zones/europe-west1-b/networkEndpointGroups/webapp-neg-80
  - balancingMode: RATE
    maxRatePerEndpoint: 100
    group:
      networkEndpointGroupRef:
        external: projects/u2i-tenant-webapp/zones/europe-west1-c/networkEndpointGroups/webapp-neg-80
  - balancingMode: RATE
    maxRatePerEndpoint: 100
    group:
      networkEndpointGroupRef:
        external: projects/u2i-tenant-webapp/zones/europe-west1-d/networkEndpointGroups/webapp-neg-80
---
# Certificate Manager - Managed certificate with DNS challenge
apiVersion: certificatemanager.cnrm.cloud.google.com/v1beta1
kind: CertificateManagerCertificate
metadata:
  name: webapp-cert
  annotations:
    cnrm.cloud.google.com/project-id: u2i-tenant-webapp
spec:
  projectRef:
    external: u2i-tenant-webapp
  location: global
  managed:
    domains:
    - dev.webapp.u2i.dev
    dnsAuthorizationsRefs:
    - name: webapp-auth
---
# DNS Authorization for certificate
apiVersion: certificatemanager.cnrm.cloud.google.com/v1beta1
kind: CertificateManagerDNSAuthorization
metadata:
  name: webapp-auth
  annotations:
    cnrm.cloud.google.com/project-id: u2i-tenant-webapp
spec:
  projectRef:
    external: u2i-tenant-webapp
  domain: dev.webapp.u2i.dev
---
# Certificate Map
apiVersion: certificatemanager.cnrm.cloud.google.com/v1beta1
kind: CertificateManagerCertificateMap
metadata:
  name: webapp-cert-map
  annotations:
    cnrm.cloud.google.com/project-id: u2i-tenant-webapp
spec:
  projectRef:
    external: u2i-tenant-webapp
---
# Certificate Map Entry
apiVersion: certificatemanager.cnrm.cloud.google.com/v1beta1
kind: CertificateManagerCertificateMapEntry
metadata:
  name: webapp-entry
  annotations:
    cnrm.cloud.google.com/project-id: u2i-tenant-webapp
spec:
  projectRef:
    external: u2i-tenant-webapp
  mapRef:
    name: webapp-cert-map
  hostname: dev.webapp.u2i.dev
  certificatesRefs:
  - name: webapp-cert
---
# URL Map for L7 routing
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeURLMap
metadata:
  name: webapp-url-map
  annotations:
    cnrm.cloud.google.com/project-id: u2i-tenant-webapp
spec:
  location: global
  defaultService:
    backendServiceRef:
      name: webapp-l7-backend
---
# Target HTTPS Proxy
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeTargetHTTPSProxy
metadata:
  name: webapp-https-proxy
  annotations:
    cnrm.cloud.google.com/project-id: u2i-tenant-webapp
spec:
  location: global
  urlMapRef:
    name: webapp-url-map
  certificateMapRef:
    external: //certificatemanager.googleapis.com/projects/u2i-tenant-webapp/locations/global/certificateMaps/webapp-cert-map
---
# Forwarding Rule for L7 HTTPS
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeForwardingRule
metadata:
  name: webapp-https-forwarding
  annotations:
    cnrm.cloud.google.com/project-id: u2i-tenant-webapp
    external-dns.alpha.kubernetes.io/hostname: dev.webapp.u2i.dev
    external-dns.alpha.kubernetes.io/ttl: "300"
spec:
  location: global
  loadBalancingScheme: EXTERNAL_MANAGED
  ipProtocol: TCP
  portRange: "443"
  target:
    targetHTTPSProxyRef:
      name: webapp-https-proxy
  ipAddress:
    addressRef:
      name: webapp-dev-ip
