apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: webapp-dev

resources:
- ../../base
- gateway-resources.yaml

patches:
- path: service-patch.yaml
  target:
    kind: Service
    name: webapp-service
- target:
    kind: Deployment
    name: webapp
  patch: |-
    - op: replace
      path: /spec/replicas
      value: 2
    - op: replace
      path: /spec/template/spec/containers/0/env/1/value
      value: nonprod

configMapGenerator:
- name: webapp-config
  literals:
    - BOUNDARY=nonprod
    - LOG_LEVEL=debug