apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: webapp-team

resources:
- ../../base
- config-connector-resources.yaml

patches:
- target:
    kind: Deployment
    name: webapp
  patch: |-
    - op: replace
      path: /spec/replicas
      value: 2
    - op: replace
      path: /spec/template/spec/containers/0/env/1/value
      value: non-prod
- target:
    kind: Service
    name: webapp-service
  patch: |-
    - op: add
      path: /metadata/annotations/external-dns.alpha.kubernetes.io~1hostname
      value: dev.webapp.u2i.dev
    - op: add
      path: /metadata/annotations/external-dns.alpha.kubernetes.io~1ttl
      value: "300"
    - op: add
      path: /metadata/annotations/external-dns.alpha.kubernetes.io~1target
      value: webapp-dev-ip

configMapGenerator:
- name: webapp-config
  literals:
    - ENVIRONMENT=non-prod
    - LOG_LEVEL=debug