apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Preview tier: minimal resources for PR previews
patches:
- target:
    kind: Deployment
    name: webapp
  patch: |-
    - op: replace
      path: /spec/replicas
      value: 1
    - op: replace
      path: /spec/template/spec/containers/0/resources
      value:
        requests:
          memory: "64Mi"
          cpu: "25m"
        limits:
          memory: "128Mi"
          cpu: "100m"