apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# KCC resources for production environment
# These are deployed with statusCheck disabled to avoid Skaffold bug #7207

resources:
- certificate-resources.yaml

# Common labels for all KCC resources
commonLabels:
  app.kubernetes.io/component: webapp
  environment: prod
  compliance: iso27001-soc2-gdpr
  data-residency: eu