apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

# Production AlloyDB configuration component
# Configures connection to managed AlloyDB instance

resources:
- external-secret.yml

configMapGenerator:
- name: webapp-database-config
  literals:
  - ENABLE_DATABASE=true
  - DATABASE_HOST=webapp-prod.alloydb.internal
  - DATABASE_PORT=5432
  - DATABASE_SSL_MODE=require
  - DATABASE_POOL_SIZE=20
  - DATABASE_IDLE_TIMEOUT=10000
  - DATABASE_CONNECTION_TIMEOUT=5000