# Base Certificate template for Config Connector
# This template is used by all environments that need SSL certificates
---
# Google-managed certificate for the domain
apiVersion: certificatemanager.cnrm.cloud.google.com/v1beta1
kind: CertificateManagerCertificate
metadata:
  name: webapp-cert
  namespace: webapp-default
  annotations:
    cnrm.cloud.google.com/project-id: PLACEHOLDER
spec:
  projectRef:
    external: PLACEHOLDER
  location: global
  description: Certificate for webapp
  managed:
    domains:
    - example.com

---
# Certificate map entry to associate certificate with the map
apiVersion: certificatemanager.cnrm.cloud.google.com/v1beta1
kind: CertificateManagerCertificateMapEntry  
metadata:
  name: webapp-entry
  namespace: webapp-default
  annotations:
    cnrm.cloud.google.com/project-id: PLACEHOLDER
spec:
  projectRef:
    external: PLACEHOLDER
  mapRef:
    name: webapp-cert-map
    namespace: infra-gw
  certificatesRefs:
  - name: webapp-cert
  hostname: example.com