# Base Certificate template for Config Connector
# This template is used by all environments that need SSL certificates
---
# Google-managed certificate for the domain
apiVersion: certificatemanager.cnrm.cloud.google.com/v1beta1
kind: CertificateManagerCertificate
metadata:
  name: ${CERT_NAME} # from-param: ${CERT_NAME}
  namespace: webapp-resources
  annotations:
    cnrm.cloud.google.com/project-id: ${PROJECT_ID} # from-param: ${PROJECT_ID}
spec:
  projectRef:
    external: ${PROJECT_ID} # from-param: ${PROJECT_ID}
  location: global
  description: ${CERT_DESCRIPTION} # from-param: ${CERT_DESCRIPTION}
  managed:
    domains:
    - ${DOMAIN} # from-param: ${DOMAIN}

---
# Certificate map entry to associate certificate with the map
apiVersion: certificatemanager.cnrm.cloud.google.com/v1beta1
kind: CertificateManagerCertificateMapEntry  
metadata:
  name: ${CERT_ENTRY_NAME} # from-param: ${CERT_ENTRY_NAME}
  namespace: webapp-resources
  annotations:
    cnrm.cloud.google.com/project-id: ${PROJECT_ID} # from-param: ${PROJECT_ID}
spec:
  projectRef:
    external: ${PROJECT_ID} # from-param: ${PROJECT_ID}
  mapRef:
    name: webapp-cert-map
    namespace: infra-gw
  certificatesRefs:
  - name: ${CERT_NAME} # from-param: ${CERT_NAME}
  hostname: ${DOMAIN} # from-param: ${DOMAIN}