apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: webapp-team

resources:
- namespace.yaml
- deployment.yaml
- service.yaml
- network-policy.yaml

# Use labels instead of commonLabels to avoid modifying selectors
# commonLabels would add these to selectors which breaks the service
labels:
- pairs:
    tenant: webapp-team
    compliance: iso27001-soc2-gdpr
    data-residency: eu
  includeSelectors: false
# Keep app label in deployment/pod templates only, not in selectors