apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
- network-policy.yaml
- gateway-route.yaml
# Note: namespace.yaml is handled separately by Cloud Deploy
# Note: pod-disruption-budget.yaml is only added in production overlay

# Use labels instead of commonLabels to avoid modifying selectors
# commonLabels would add these to selectors which breaks the service
labels:
- pairs:
    app.kubernetes.io/component: webapp
    tenant: webapp-team
    compliance: iso27001-soc2-gdpr
    data-residency: eu
  includeSelectors: false
# Keep app label in deployment/pod templates only, not in selectors