apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: webapp-pdb
  namespace: ${NAMESPACE} # from-param: ${NAMESPACE}
spec:
  minAvailable: ${PDB_MIN_AVAILABLE} # from-param: ${PDB_MIN_AVAILABLE}
  selector:
    matchLabels:
      app: webapp
  # Allow disruption during maintenance windows
  unhealthyPodEvictionPolicy: AlwaysAllow