apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: webapp-pdb
  namespace: ${NAMESPACE} # from-param: ${NAMESPACE}
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: webapp
      app.kubernetes.io/component: webapp
  # Allow disruption during maintenance windows
  unhealthyPodEvictionPolicy: AlwaysAllow