apiVersion: v1
kind: Service
metadata:
  name: webapp-service
  annotations:
    # Enable NEG creation by GKE
    cloud.google.com/neg: '{"exposed_ports": {"80": {}}}'
    # Autoneg controller will attach NEGs to backend service
    controller.autoneg.dev/neg: |
      {"backend_services":{"80":[{"name":"webapp-dev-backend","max_connections_per_endpoint":100}]}}
spec:
  type: ClusterIP
  selector:
    app: webapp
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http