apiVersion: v1
kind: Service
metadata:
  name: webapp-service
  namespace: ${NAMESPACE} # from-param: ${NAMESPACE}
spec:
  type: NodePort
  selector:
    app: webapp
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http