apiVersion: v1
kind: Service
metadata:
  name: webapp-service
  annotations:
    # Enable NEG for Config Connector L4 LB
    cloud.google.com/neg: '{"exposed_ports": {"80": {"name": "webapp-neg"}}}'
spec:
  type: ClusterIP
  selector:
    app: webapp
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http