# Compliance CLI configuration for webapp-team-app
# All fields are required

# Application identifier
app: webapp

# GCP projects
projects:
  nonprod: u2i-tenant-webapp-nonprod
  prod: u2i-tenant-webapp-prod

# Domain configuration  
domains:
  nonprod_base: u2i.dev
  prod_base: u2i.com

# Test configuration
tests:
  # Enable or disable test execution in pipelines
  enabled: true
  
  # Docker image to use for running tests
  runner_image: node:18-alpine
  
  # Commands to execute for testing
  commands:
    install: npm ci
    test: npm run test:ci
    
  # Success message to display after tests pass
  success_message: "Tests passed successfully!"
  
  # Whether to fail the build if tests fail
  fail_on_error: true

# Static Analysis configuration
analysis:
  enabled: true
  runner_image: node:18-alpine
  commands:
    install: npm ci
    analyze: |
      npm audit --audit-level=high
      npx eslint . --ext .js,.jsx,.ts,.tsx --max-warnings 0 || true
  success_message: "Static analysis completed!"
  fail_on_error: false  # Set to true to block on security issues

# Lint configuration
lint:
  enabled: true
  runner_image: node:18-alpine
  commands:
    install: npm ci
    lint: npx eslint . --ext .js,.jsx,.ts,.tsx
  success_message: "Linting passed!"
  fail_on_error: true

# Format configuration  
format:
  enabled: true
  runner_image: node:18-alpine
  commands:
    install: npm ci
    check: npx prettier --check "**/*.{js,jsx,ts,tsx,json,css,md}"
  success_message: "Code formatting verified!"
  fail_on_error: false  # Usually just a warning