# Cloud Deploy Configuration for Preview Deployments
# Supports dynamic domains like foo.webapp.u2i.dev

apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: webapp-preview-pipeline
  labels:
    compliance: iso27001-soc2-gdpr
    team: webapp-team
    purpose: preview
description: "Preview deployment pipeline with parameterized domains"

serialPipeline:
  stages:
  # Stage 1: Create certificate and wait for it to be ready
  - targetId: preview-gke-cert
    profiles: ["cert-only"]
    strategy:
      standard:
        verify: false
  
  # Stage 2: Deploy infrastructure (service, configmap, routes)
  - targetId: preview-gke-infra
    profiles: ["infra-only"]
    strategy:
      standard:
        verify: false
  
  # Stage 3: Deploy the application
  - targetId: preview-gke-app
    profiles: ["app-only"]
    strategy:
      standard:
        verify: false

---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: preview-gke-cert
  labels:
    compliance: iso27001-soc2-gdpr
    environment: preview
    data-residency: eu
    stage: certificate
description: "Certificate provisioning stage"

gke:
  cluster: projects/u2i-tenant-webapp/locations/europe-west1/clusters/webapp-cluster
  
executionConfigs:
- usages: [RENDER, DEPLOY]
  serviceAccount: cloud-deploy-sa@u2i-tenant-webapp.iam.gserviceaccount.com
  artifactStorage: gs://u2i-tenant-webapp-deploy-artifacts

---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: preview-gke-infra
  labels:
    compliance: iso27001-soc2-gdpr
    environment: preview
    data-residency: eu
    stage: infrastructure
description: "Infrastructure deployment stage"

gke:
  cluster: projects/u2i-tenant-webapp/locations/europe-west1/clusters/webapp-cluster
  
executionConfigs:
- usages: [RENDER, DEPLOY]
  serviceAccount: cloud-deploy-sa@u2i-tenant-webapp.iam.gserviceaccount.com
  artifactStorage: gs://u2i-tenant-webapp-deploy-artifacts

---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: preview-gke-app
  labels:
    compliance: iso27001-soc2-gdpr
    environment: preview
    data-residency: eu
    stage: application
description: "Application deployment stage"

gke:
  cluster: projects/u2i-tenant-webapp/locations/europe-west1/clusters/webapp-cluster
  
executionConfigs:
- usages: [RENDER, DEPLOY]
  serviceAccount: cloud-deploy-sa@u2i-tenant-webapp.iam.gserviceaccount.com
  artifactStorage: gs://u2i-tenant-webapp-deploy-artifacts

---
apiVersion: deploy.cloud.google.com/v1
kind: Automation
metadata:
  name: webapp-preview-pipeline/promote-cert-to-infra
  labels:
    compliance: iso27001-soc2-gdpr
description: "Auto-promote from cert to infra stage when cert is ready"
suspended: false
serviceAccount: cloud-deploy-sa@u2i-tenant-webapp.iam.gserviceaccount.com
selector:
- target:
    id: preview-gke-cert
rules:
- promoteReleaseRule:
    id: promote-to-infra
    wait: 1m
    toTargetId: preview-gke-infra

---
apiVersion: deploy.cloud.google.com/v1
kind: Automation
metadata:
  name: webapp-preview-pipeline/promote-infra-to-app
  labels:
    compliance: iso27001-soc2-gdpr
description: "Auto-promote from infra to app stage when infra is ready"
suspended: false
serviceAccount: cloud-deploy-sa@u2i-tenant-webapp.iam.gserviceaccount.com
selector:
- target:
    id: preview-gke-infra
rules:
- promoteReleaseRule:
    id: promote-to-app
    wait: 1m
    toTargetId: preview-gke-app