# Cloud Deploy Configuration for Dev Environment
# Single stage deployment with kubectl for proper sequencing

apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: webapp-dev-pipeline
  labels:
    compliance: iso27001-soc2-gdpr
    team: webapp-team
    purpose: development
description: "Dev deployment pipeline with single stage"

serialPipeline:
  stages:
  - targetId: dev-gke
    profiles: ["dev"]
    strategy:
      standard:
        verify: false

---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: dev-gke
  labels:
    compliance: iso27001-soc2-gdpr
    environment: dev
    data-residency: eu
description: "Dev deployment target"

gke:
  cluster: projects/u2i-tenant-webapp-nonprod/locations/europe-west1/clusters/webapp-cluster
  
executionConfigs:
- usages: [RENDER, DEPLOY]
  serviceAccount: cloud-deploy-sa@u2i-tenant-webapp-nonprod.iam.gserviceaccount.com
  artifactStorage: gs://u2i-tenant-webapp-nonprod-deploy-artifacts