steps:
# Extract PR number from the pull request
- name: 'gcr.io/cloud-builders/gcloud'
  id: 'get-pr-number'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    # Try different methods to get PR number
    # Method 1: Direct from Cloud Build (if available)
    if [ -n "${_PR_NUMBER:-}" ]; then
      echo "${_PR_NUMBER}" > /workspace/pr_number.txt
      echo "Using _PR_NUMBER from Cloud Build: ${_PR_NUMBER}"
    # Method 2: From branch name
    elif [ -n "${_HEAD_BRANCH:-}" ]; then
      if [[ "${_HEAD_BRANCH}" =~ ^[0-9]+$ ]]; then
        echo "${_HEAD_BRANCH}" > /workspace/pr_number.txt
        echo "Extracted PR number from head branch: ${_HEAD_BRANCH}"
      elif [[ "${_HEAD_BRANCH}" =~ pr-([0-9]+) ]]; then
        echo "${BASH_REMATCH[1]}" > /workspace/pr_number.txt
        echo "Extracted PR number from head branch pattern: ${BASH_REMATCH[1]}"
      fi
    fi
    
    # Method 3: From commit message
    if [ ! -f /workspace/pr_number.txt ]; then
      PR_FROM_COMMIT=$(git log -1 --pretty=%B | grep -oE '#[0-9]+' | head -1 | tr -d '#')
      if [ -n "$PR_FROM_COMMIT" ]; then
        echo "$PR_FROM_COMMIT" > /workspace/pr_number.txt
        echo "Extracted PR number from commit message: $PR_FROM_COMMIT"
      fi
    fi
    
    # Fallback to short SHA
    if [ ! -f /workspace/pr_number.txt ]; then
      echo "$SHORT_SHA" > /workspace/pr_number.txt
      echo "WARNING: Could not determine PR number, using commit SHA: $SHORT_SHA"
    fi
    
    echo "Final PR identifier: $(cat /workspace/pr_number.txt)"

# Build the Docker image
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    PR_ID=$(cat /workspace/pr_number.txt)
    docker build \
      -t ${_REGION}-docker.pkg.dev/${_PROJECT_ID}/webapp-images/webapp:preview-$COMMIT_SHA \
      -t ${_REGION}-docker.pkg.dev/${_PROJECT_ID}/webapp-images/webapp:preview-pr$PR_ID \
      .

# Push the Docker image
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', '--all-tags', '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/webapp-images/webapp']

# Deploy using Cloud Deploy
- name: 'google/cloud-sdk:alpine'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    PR_ID=$(cat /workspace/pr_number.txt)
    PREVIEW_NAME="pr-$PR_ID"
    DOMAIN="$PREVIEW_NAME.webapp.u2i.dev"
    NAMESPACE="webapp-preview-$PREVIEW_NAME"
    
    # Create Cloud Deploy release for preview
    gcloud deploy releases create "preview-$PREVIEW_NAME-$SHORT_SHA" \
      --delivery-pipeline=webapp-preview-pipeline \
      --region=${_REGION} \
      --project=${_PROJECT_ID} \
      --images="webapp=${_REGION}-docker.pkg.dev/${_PROJECT_ID}/webapp-images/webapp:preview-$COMMIT_SHA" \
      --to-target=preview-gke \
      --skaffold-file=skaffold-gateway-preview.yaml \
      --deploy-parameters="NAMESPACE=$NAMESPACE,ENV=preview,API_URL=https://api-$DOMAIN,STAGE=preview,BOUNDARY=nonprod,TIER=preview,NAME_PREFIX=preview-,DOMAIN=$DOMAIN,ROUTE_NAME=webapp-preview-route-$PREVIEW_NAME,SERVICE_NAME=webapp-service,CERT_NAME=webapp-preview-cert-$PREVIEW_NAME,CERT_ENTRY_NAME=webapp-preview-entry-$PREVIEW_NAME,CERT_DESCRIPTION=Certificate for $DOMAIN"
    
    echo "✅ Preview deployment initiated: https://$DOMAIN"

# Post comment on PR
- name: 'google/cloud-sdk:alpine'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    PR_ID=$(cat /workspace/pr_number.txt)
    PREVIEW_NAME="pr-$PR_ID"
    PREVIEW_URL="https://$PREVIEW_NAME.webapp.u2i.dev"
    BUILD_URL="https://console.cloud.google.com/cloud-build/builds;region=${_REGION}/$BUILD_ID?project=${_PROJECT_ID}"
    
    # Get GitHub OAuth token
    GITHUB_TOKEN=$(gcloud secrets versions access latest --secret=u2i-github-github-oauthtoken-3517b7 --project=u2i-bootstrap)
    
    if [ -n "$GITHUB_TOKEN" ]; then
      # Only post comment if we have a numeric PR number
      if [[ "$PR_ID" =~ ^[0-9]+$ ]]; then
        curl -X POST \
          -H "Authorization: token $GITHUB_TOKEN" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/u2i/webapp-team-app/issues/$PR_ID/comments \
          -d "{
            \"body\": \"🚀 **Preview deployment started!**\\n\\nYour preview will be available at: $PREVIEW_URL\\n\\nDeployment usually takes 5-10 minutes to complete.\\n\\n[View Build]($BUILD_URL)\"
          }"
      else
        echo "Skipping PR comment - not a numeric PR number: $PR_ID"
      fi
    fi

options:
  logging: CLOUD_LOGGING_ONLY
  dynamicSubstitutions: true
  
substitutions:
  _PROJECT_ID: u2i-tenant-webapp-nonprod
  _REGION: europe-west1