steps:
# Extract PR number from the pull request
- name: 'gcr.io/cloud-builders/gcloud'
  id: 'get-pr-number'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    set -e  # Exit on error
    
    # Debug: Print all available substitutions
    echo "=== Cloud Build Substitutions ==="
    echo "COMMIT_SHA: $COMMIT_SHA"
    echo "SHORT_SHA: $SHORT_SHA"
    echo "_PR_NUMBER: ${_PR_NUMBER:-not set}"
    echo "_HEAD_BRANCH: ${_HEAD_BRANCH:-not set}"
    echo "_BASE_BRANCH: ${_BASE_BRANCH:-not set}"
    echo "BRANCH_NAME: ${BRANCH_NAME:-not set}"
    echo "================================"
    
    # Get GitHub OAuth token for API calls
    gcloud secrets versions access latest --secret=u2i-github-github-oauthtoken-3517b7 --project=u2i-bootstrap > /tmp/github_token
    
    # Method 1: Get PR number from GitHub API using commit SHA
    echo "Checking GitHub API for PR associated with commit $COMMIT_SHA..."
    PR_NUMBER=`curl -s -H "Authorization: token $(cat /tmp/github_token)" \
      "https://api.github.com/repos/u2i/webapp-team-app/commits/$COMMIT_SHA/pulls" | \
      jq -r '.[0].number // empty' || true`
    
    if [ -n "$PR_NUMBER" ] && [ "$PR_NUMBER" != "null" ]; then
      echo "$PR_NUMBER" > /workspace/pr_number.txt
      echo "Found PR #$PR_NUMBER from GitHub API"
    else
      # Fallback to commit SHA
      echo "$SHORT_SHA" > /workspace/pr_number.txt
      echo "WARNING: Could not determine PR number, using commit SHA: $SHORT_SHA"
    fi
    
    echo "Final PR identifier: `cat /workspace/pr_number.txt`"

# Build the Docker image
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    set -e  # Exit on error
    docker build \
      -t ${_REGION}-docker.pkg.dev/${_PROJECT_ID}/webapp-images/webapp:preview-$COMMIT_SHA \
      -t ${_REGION}-docker.pkg.dev/${_PROJECT_ID}/webapp-images/webapp:preview-pr`cat /workspace/pr_number.txt` \
      .

# Push the Docker image
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', '--all-tags', '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/webapp-images/webapp']

# Deploy using Cloud Deploy
- name: 'google/cloud-sdk:alpine'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    set -e  # Exit on error
    gcloud deploy releases create "preview-pr`cat /workspace/pr_number.txt`-$SHORT_SHA" \
      --delivery-pipeline=webapp-preview-pipeline \
      --region=${_REGION} \
      --project=${_PROJECT_ID} \
      --images="${_REGION}-docker.pkg.dev/${_PROJECT_ID}/webapp-images/webapp=${_REGION}-docker.pkg.dev/${_PROJECT_ID}/webapp-images/webapp:preview-$COMMIT_SHA" \
      --to-target=preview-gke \
      --skaffold-file=skaffold-preview-deploy.yaml \
      --deploy-parameters="NAMESPACE=webapp-preview-pr`cat /workspace/pr_number.txt`,ENV=preview,API_URL=https://api-pr`cat /workspace/pr_number.txt`.webapp.u2i.dev,STAGE=preview,BOUNDARY=nonprod,TIER=preview,NAME_PREFIX=preview-,DOMAIN=pr`cat /workspace/pr_number.txt`.webapp.u2i.dev,ROUTE_NAME=webapp-preview-route-pr`cat /workspace/pr_number.txt`,SERVICE_NAME=webapp-service,CERT_NAME=webapp-preview-cert-pr`cat /workspace/pr_number.txt`,CERT_ENTRY_NAME=webapp-preview-entry-pr`cat /workspace/pr_number.txt`,CERT_DESCRIPTION=Certificate for pr`cat /workspace/pr_number.txt`.webapp.u2i.dev" \
      --impersonate-service-account=cloud-deploy-sa@${_PROJECT_ID}.iam.gserviceaccount.com
    
    echo "✅ Preview deployment initiated: https://pr`cat /workspace/pr_number.txt`.webapp.u2i.dev"

# Post comment on PR
- name: 'google/cloud-sdk:alpine'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    set -e  # Exit on error
    # Get GitHub OAuth token
    gcloud secrets versions access latest --secret=u2i-github-github-oauthtoken-3517b7 --project=u2i-bootstrap > /tmp/github_token
    
    if [ -s /tmp/github_token ]; then
      # Only post comment if we have a numeric PR number
      if [[ "`cat /workspace/pr_number.txt`" =~ ^[0-9]+$ ]]; then
        curl -X POST \
          -H "Authorization: token `cat /tmp/github_token`" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/u2i/webapp-team-app/issues/`cat /workspace/pr_number.txt`/comments \
          -d "{
            \"body\": \"🚀 **Preview deployment started!**\\n\\nYour preview will be available at: https://pr`cat /workspace/pr_number.txt`.webapp.u2i.dev\\n\\nDeployment usually takes 5-10 minutes to complete.\\n\\n[View Build](https://console.cloud.google.com/cloud-build/builds;region=${_REGION}/$BUILD_ID?project=${_PROJECT_ID})\"
          }"
      else
        echo "Skipping PR comment - not a numeric PR number: `cat /workspace/pr_number.txt`"
      fi
    fi

options:
  logging: CLOUD_LOGGING_ONLY
  dynamicSubstitutions: true
  
substitutions:
  _PROJECT_ID: u2i-tenant-webapp-nonprod
  _REGION: europe-west1