# Cloud Deploy Configuration for Preview Deployments
# Supports dynamic domains like foo.webapp.u2i.dev

apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: webapp-preview-pipeline
  labels:
    compliance: iso27001-soc2-gdpr
    team: webapp-team
    purpose: preview
description: "Preview deployment pipeline with parameterized domains"

serialPipeline:
  stages:
  - targetId: preview-gke

---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: preview-gke
  labels:
    compliance: iso27001-soc2-gdpr
    environment: preview
    data-residency: eu
description: "Preview deployments on nonprod GKE cluster"

gke:
  cluster: projects/u2i-tenant-webapp/locations/europe-west1/clusters/webapp-cluster
  
executionConfigs:
- usages: [RENDER, DEPLOY]
  serviceAccount: cloud-deploy-sa@u2i-tenant-webapp.iam.gserviceaccount.com
  artifactStorage: gs://u2i-tenant-webapp-deploy-artifacts