# Cloud Deploy Configuration for QA to Production Pipeline
# QA deploys automatically, Production requires approval

apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: webapp-qa-prod-pipeline
  labels:
    compliance: iso27001-soc2-gdpr
    team: webapp-team
    purpose: production
description: "QA to Production pipeline with approval gate"

serialPipeline:
  stages:
  # QA stage - automatic deployment
  - targetId: qa-gke
    profiles: ["qa"]
    strategy:
      standard:
        verify: false
        
  # Production stage - requires approval
  - targetId: prod-gke
    profiles: ["prod"]
    strategy:
      standard:
        verify: false

---
# QA Target
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: qa-gke
  labels:
    compliance: iso27001-soc2-gdpr
    environment: qa
    data-residency: eu
description: "QA deployment target"
spec:
  requireApproval: false
  gke:
    cluster: projects/u2i-tenant-webapp-nonprod/locations/europe-west1/clusters/webapp-cluster
  executionConfigs:
  - usages: [RENDER, DEPLOY]
    serviceAccount: cloud-deploy-sa@u2i-tenant-webapp-nonprod.iam.gserviceaccount.com
    artifactStorage: gs://u2i-tenant-webapp-nonprod-deploy-artifacts

---
# Production Target
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: prod-gke
  labels:
    compliance: iso27001-soc2-gdpr
    environment: prod
    data-residency: eu
description: "Production deployment target"
spec:
  requireApproval: true
  gke:
    cluster: projects/u2i-tenant-webapp-prod/locations/europe-west1/clusters/webapp-cluster-prod
  executionConfigs:
  - usages: [RENDER, DEPLOY]
    serviceAccount: cloud-deploy-sa@u2i-tenant-webapp-prod.iam.gserviceaccount.com
    artifactStorage: gs://u2i-tenant-webapp-prod-deploy-artifacts