# Cloud Deploy Configuration for Preview Deployments
# Consolidated single-stage deployment: cert → infra → app

apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: webapp-preview-pipeline
  labels:
    compliance: iso27001-soc2-gdpr
    team: webapp-team
    purpose: preview
description: "Preview deploy: cert → infra → app as one unit"

serialPipeline:
  stages:
  - targetId: preview-gke
    # Run these three Skaffold profiles in order as one stage
    profiles: ["cert-only", "infra-only", "app-only"]
    strategy:
      standard:
        verify: false
    deployParameters:
    - values:
        DOMAIN: ""
        PREVIEW_NAME: ""
        NAMESPACE: ""
        CERT_NAME: ""
        CERT_ENTRY_NAME: ""
        CERT_DESCRIPTION: ""
        ROUTE_NAME: ""
        API_URL: ""
        ENV: ""
        STAGE: ""
        BOUNDARY: ""
        TIER: ""
        NAME_PREFIX: ""
        SERVICE_NAME: ""

---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: preview-gke
  labels:
    compliance: iso27001-soc2-gdpr
    environment: preview
    data-residency: eu
description: "All-in-one preview stage"

gke:
  cluster: projects/u2i-tenant-webapp/locations/europe-west1/clusters/webapp-cluster
  
executionConfigs:
- usages: [RENDER, DEPLOY]
  serviceAccount: cloud-deploy-sa@u2i-tenant-webapp.iam.gserviceaccount.com
  artifactStorage: gs://u2i-tenant-webapp-deploy-artifacts