# Cloud Deploy Configuration for WebApp
# Two pipelines: qa-prod (with approval) and other (for dev/preview)

apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: webapp-qa-prod-pipeline
  labels:
    team: webapp-team
    purpose: production
    compliance: iso27001-soc2-gdpr
description: "QA to Production pipeline with approval"

serialPipeline:
  stages:
  - targetId: qa
    profiles: ["preprod"]
    strategy:
      standard:
        verify: true
        
  - targetId: prod
    profiles: ["prod"]
    strategy:
      standard:
        verify: true

---
apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: webapp-dev-pipeline
  labels:
    team: webapp-team
    purpose: development
description: "Pipeline for dev environment continuous deployment"

serialPipeline:
  stages:
  - targetId: dev
    profiles: ["preprod"]
    strategy:
      standard:
        verify: false

---
# QA Target
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: qa
  labels:
    environment: qa
    compliance: iso27001-soc2-gdpr
    data-residency: eu
requireApproval: false

gke:
  cluster: projects/u2i-tenant-webapp/locations/europe-west1/clusters/webapp-cluster

executionConfigs:
- usages: [RENDER, DEPLOY, VERIFY]
  serviceAccount: cloud-deploy-sa@u2i-tenant-webapp.iam.gserviceaccount.com
  artifactStorage: gs://u2i-tenant-webapp-deploy-artifacts

---
# Production Target
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: prod
  labels:
    environment: prod
    compliance: iso27001-soc2-gdpr
    data-residency: eu
requireApproval: true

gke:
  cluster: projects/u2i-tenant-webapp-prod/locations/europe-west1/clusters/webapp-cluster-prod

executionConfigs:
- usages: [RENDER, DEPLOY, VERIFY]
  serviceAccount: cloud-deploy-sa@u2i-tenant-webapp-prod.iam.gserviceaccount.com
  artifactStorage: gs://u2i-tenant-webapp-prod-deploy-artifacts

---
# Dev Target
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: dev
  labels:
    environment: dev
    compliance: iso27001-soc2-gdpr
    data-residency: eu

gke:
  cluster: projects/u2i-tenant-webapp/locations/europe-west1/clusters/webapp-cluster

executionConfigs:
- usages: [RENDER, DEPLOY]
  serviceAccount: cloud-deploy-sa@u2i-tenant-webapp.iam.gserviceaccount.com
  artifactStorage: gs://u2i-tenant-webapp-deploy-artifacts

---
# Keep the existing preview pipeline as is
# It's already well-structured with 3 stages for certificate provisioning