# Cloud Deploy Configuration for webapp-team
# Deploys to GKE clusters with compliance controls

apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: webapp-delivery-pipeline
  labels:
    compliance: iso27001-soc2-gdpr
    team: webapp-team
    data-residency: eu
spec:
  description: "Delivery pipeline for webapp with dev/prod stages"
  
  serialPipeline:
    stages:
    # Non-prod stage (includes dev)
    - targetId: nonprod-gke
      profiles: [non-prod]
      deployParameters:
      - name: environment
        values: [non-prod]
      
    # Production stage
    - targetId: prod-gke
      profiles: [prod]
      deployParameters:
      - name: environment
        values: [production]
      strategy:
        standard:
          verify: true
          predeploy:
            actions:
            - name: security-validation
            - name: compliance-audit
          postdeploy:
            actions:
            - name: health-verification

---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: nonprod-gke
  labels:
    compliance: iso27001-soc2-gdpr
    environment: non-production
    data-residency: eu
spec:
  description: "Non-production GKE cluster (includes dev)"
  
  gke:
    cluster: projects/u2i-tenant-webapp/locations/europe-west1/clusters/webapp-cluster
    
  executionConfigs:
  - usages: [RENDER, DEPLOY, VERIFY]
    serviceAccount: cloud-deploy-sa@u2i-tenant-webapp.iam.gserviceaccount.com
    artifactStorage: gs://u2i-tenant-webapp-deploy-artifacts

---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: prod-gke
  labels:
    compliance: iso27001-soc2-gdpr
    environment: production
    data-residency: eu
    critical: "true"
spec:
  description: "Production GKE cluster with strict compliance"
  
  gke:
    cluster: projects/u2i-tenant-webapp-prod/locations/europe-west1/clusters/webapp-cluster-prod
    
  executionConfigs:
  - usages: [RENDER, DEPLOY, VERIFY]
    serviceAccount: cloud-deploy-sa@u2i-tenant-webapp.iam.gserviceaccount.com
    artifactStorage: gs://u2i-tenant-webapp-deploy-artifacts
    
  requireApproval: true