# Cloud Deploy Configuration with 3-stage deployment for all environments
# Pattern: cert → infra → app

apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: webapp-dev-pipeline-3stage
  labels:
    team: webapp-team
    purpose: development
description: "Dev pipeline with 3-stage deployment"

serialPipeline:
  stages:
  - targetId: dev-cert
    profiles: ["dev-cert"]
    strategy:
      standard:
        verify: false
  
  - targetId: dev-infra
    profiles: ["dev-infra"]
    strategy:
      standard:
        verify: false
  
  - targetId: dev-app
    profiles: ["dev-app"]
    strategy:
      standard:
        verify: false

---
apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: webapp-qa-prod-pipeline-3stage
  labels:
    team: webapp-team
    purpose: production
    compliance: iso27001-soc2-gdpr
description: "QA to Production pipeline with 3-stage deployment and approval"

serialPipeline:
  stages:
  # QA stages
  - targetId: qa-cert
    profiles: ["qa-cert"]
    strategy:
      standard:
        verify: false
        
  - targetId: qa-infra
    profiles: ["qa-infra"]
    strategy:
      standard:
        verify: false
        
  - targetId: qa-app
    profiles: ["qa-app"]
    strategy:
      standard:
        verify: true
        
  # Production stages
  - targetId: prod-cert
    profiles: ["prod-cert"]
    strategy:
      standard:
        verify: false
        
  - targetId: prod-infra
    profiles: ["prod-infra"]
    strategy:
      standard:
        verify: false
        
  - targetId: prod-app
    profiles: ["prod-app"]
    strategy:
      standard:
        verify: true

---
# Dev Targets
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: dev-cert
  labels:
    environment: dev
    stage: certificate
requireApproval: false
gke:
  cluster: projects/u2i-tenant-webapp-nonprod/locations/europe-west1/clusters/webapp-cluster
executionConfigs:
- usages: [RENDER, DEPLOY]
  serviceAccount: cloud-deploy-sa@u2i-tenant-webapp-nonprod.iam.gserviceaccount.com
  artifactStorage: gs://u2i-tenant-webapp-nonprod-deploy-artifacts

---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: dev-infra
  labels:
    environment: dev
    stage: infrastructure
requireApproval: false
gke:
  cluster: projects/u2i-tenant-webapp-nonprod/locations/europe-west1/clusters/webapp-cluster
executionConfigs:
- usages: [RENDER, DEPLOY]
  serviceAccount: cloud-deploy-sa@u2i-tenant-webapp-nonprod.iam.gserviceaccount.com
  artifactStorage: gs://u2i-tenant-webapp-nonprod-deploy-artifacts

---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: dev-app
  labels:
    environment: dev
    stage: application
requireApproval: false
gke:
  cluster: projects/u2i-tenant-webapp-nonprod/locations/europe-west1/clusters/webapp-cluster
executionConfigs:
- usages: [RENDER, DEPLOY]
  serviceAccount: cloud-deploy-sa@u2i-tenant-webapp-nonprod.iam.gserviceaccount.com
  artifactStorage: gs://u2i-tenant-webapp-nonprod-deploy-artifacts

---
# QA Targets
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: qa-cert
  labels:
    environment: qa
    stage: certificate
    compliance: iso27001-soc2-gdpr
    data-residency: eu
requireApproval: false
gke:
  cluster: projects/u2i-tenant-webapp-nonprod/locations/europe-west1/clusters/webapp-cluster
executionConfigs:
- usages: [RENDER, DEPLOY]
  serviceAccount: cloud-deploy-sa@u2i-tenant-webapp-nonprod.iam.gserviceaccount.com
  artifactStorage: gs://u2i-tenant-webapp-nonprod-deploy-artifacts

---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: qa-infra
  labels:
    environment: qa
    stage: infrastructure
    compliance: iso27001-soc2-gdpr
    data-residency: eu
requireApproval: false
gke:
  cluster: projects/u2i-tenant-webapp-nonprod/locations/europe-west1/clusters/webapp-cluster
executionConfigs:
- usages: [RENDER, DEPLOY]
  serviceAccount: cloud-deploy-sa@u2i-tenant-webapp-nonprod.iam.gserviceaccount.com
  artifactStorage: gs://u2i-tenant-webapp-nonprod-deploy-artifacts

---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: qa-app
  labels:
    environment: qa
    stage: application
    compliance: iso27001-soc2-gdpr
    data-residency: eu
requireApproval: false
gke:
  cluster: projects/u2i-tenant-webapp-nonprod/locations/europe-west1/clusters/webapp-cluster
executionConfigs:
- usages: [RENDER, DEPLOY, VERIFY]
  serviceAccount: cloud-deploy-sa@u2i-tenant-webapp-nonprod.iam.gserviceaccount.com
  artifactStorage: gs://u2i-tenant-webapp-nonprod-deploy-artifacts

---
# Production Targets
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: prod-cert
  labels:
    environment: prod
    stage: certificate
    compliance: iso27001-soc2-gdpr
    data-residency: eu
requireApproval: true
gke:
  cluster: projects/u2i-tenant-webapp-prod/locations/europe-west1/clusters/webapp-cluster-prod
executionConfigs:
- usages: [RENDER, DEPLOY]
  serviceAccount: cloud-deploy-sa@u2i-tenant-webapp-prod.iam.gserviceaccount.com
  artifactStorage: gs://u2i-tenant-webapp-prod-deploy-artifacts

---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: prod-infra
  labels:
    environment: prod
    stage: infrastructure
    compliance: iso27001-soc2-gdpr
    data-residency: eu
requireApproval: false
gke:
  cluster: projects/u2i-tenant-webapp-prod/locations/europe-west1/clusters/webapp-cluster-prod
executionConfigs:
- usages: [RENDER, DEPLOY]
  serviceAccount: cloud-deploy-sa@u2i-tenant-webapp-prod.iam.gserviceaccount.com
  artifactStorage: gs://u2i-tenant-webapp-prod-deploy-artifacts

---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: prod-app
  labels:
    environment: prod
    stage: application
    compliance: iso27001-soc2-gdpr
    data-residency: eu
requireApproval: false
gke:
  cluster: projects/u2i-tenant-webapp-prod/locations/europe-west1/clusters/webapp-cluster-prod
executionConfigs:
- usages: [RENDER, DEPLOY, VERIFY]
  serviceAccount: cloud-deploy-sa@u2i-tenant-webapp-prod.iam.gserviceaccount.com
  artifactStorage: gs://u2i-tenant-webapp-prod-deploy-artifacts

---
# Automations for dev pipeline
apiVersion: deploy.cloud.google.com/v1
kind: Automation
metadata:
  name: webapp-dev-pipeline-3stage/promote-cert-to-infra
  labels:
    compliance: iso27001-soc2-gdpr
description: "Auto-promote from cert to infra stage"
suspended: false
serviceAccount: cloud-deploy-sa@u2i-tenant-webapp-nonprod.iam.gserviceaccount.com
selector:
- target:
    id: dev-cert
rules:
- promoteReleaseRule:
    id: promote-to-infra
    toTargetId: dev-infra
    wait: 0s

---
apiVersion: deploy.cloud.google.com/v1
kind: Automation
metadata:
  name: webapp-dev-pipeline-3stage/promote-infra-to-app
  labels:
    compliance: iso27001-soc2-gdpr
description: "Auto-promote from infra to app stage"
suspended: false
serviceAccount: cloud-deploy-sa@u2i-tenant-webapp-nonprod.iam.gserviceaccount.com
selector:
- target:
    id: dev-infra
rules:
- promoteReleaseRule:
    id: promote-to-app
    toTargetId: dev-app
    wait: 0s

---
# Automations for QA stages only (not prod)
apiVersion: deploy.cloud.google.com/v1
kind: Automation
metadata:
  name: webapp-qa-prod-pipeline-3stage/promote-qa-cert-to-infra
  labels:
    compliance: iso27001-soc2-gdpr
description: "Auto-promote from QA cert to infra stage"
suspended: false
serviceAccount: cloud-deploy-sa@u2i-tenant-webapp-nonprod.iam.gserviceaccount.com
selector:
- target:
    id: qa-cert
rules:
- promoteReleaseRule:
    id: promote-to-infra
    toTargetId: qa-infra
    wait: 0s

---
apiVersion: deploy.cloud.google.com/v1
kind: Automation
metadata:
  name: webapp-qa-prod-pipeline-3stage/promote-qa-infra-to-app
  labels:
    compliance: iso27001-soc2-gdpr
description: "Auto-promote from QA infra to app stage"
suspended: false
serviceAccount: cloud-deploy-sa@u2i-tenant-webapp-nonprod.iam.gserviceaccount.com
selector:
- target:
    id: qa-infra
rules:
- promoteReleaseRule:
    id: promote-to-app
    toTargetId: qa-app
    wait: 0s

---
# Prod stages automation (after manual approval)
apiVersion: deploy.cloud.google.com/v1
kind: Automation
metadata:
  name: webapp-qa-prod-pipeline-3stage/promote-prod-cert-to-infra
  labels:
    compliance: iso27001-soc2-gdpr
description: "Auto-promote from prod cert to infra stage"
suspended: false
serviceAccount: cloud-deploy-sa@u2i-tenant-webapp-prod.iam.gserviceaccount.com
selector:
- target:
    id: prod-cert
rules:
- promoteReleaseRule:
    id: promote-to-infra
    toTargetId: prod-infra
    wait: 0s

---
apiVersion: deploy.cloud.google.com/v1
kind: Automation
metadata:
  name: webapp-qa-prod-pipeline-3stage/promote-prod-infra-to-app
  labels:
    compliance: iso27001-soc2-gdpr
description: "Auto-promote from prod infra to app stage"
suspended: false
serviceAccount: cloud-deploy-sa@u2i-tenant-webapp-prod.iam.gserviceaccount.com
selector:
- target:
    id: prod-infra
rules:
- promoteReleaseRule:
    id: promote-to-app
    toTargetId: prod-app
    wait: 0s