version: '3.8'

# Local test environment - extends CI config
# Usage: docker compose -f docker-compose.ci.yml -f docker-compose.test.local.yml up

services:
  # Override app-test to just keep container running for interactive testing
  app-test:
    # Keep container running for interactive testing
    command: sleep infinity
    # Enable TTY for interactive sessions
    stdin_open: true
    tty: true
    
  # PostgreSQL already configured in docker-compose.ci.yml
  # Just exposes the port for local access
  postgres-test:
    ports:
      - "5432:5432"  # Expose for local tools like pgAdmin

# Usage examples:
# 
# Start test environment:
#   docker compose -f docker-compose.ci.yml -f docker-compose.test.local.yml up -d
#
# Run tests interactively:
#   docker compose -f docker-compose.ci.yml -f docker-compose.test.local.yml exec app-test npm test
#
# Run specific test file:
#   docker compose -f docker-compose.ci.yml -f docker-compose.test.local.yml exec app-test npx jest app.test.js
#
# Access database:
#   docker compose -f docker-compose.ci.yml -f docker-compose.test.local.yml exec postgres-test psql -U postgres -d webapp_test
#
# Clean up:
#   docker compose -f docker-compose.ci.yml -f docker-compose.test.local.yml down -v