apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: webapp-namespace
# Namespace module - creates namespace for production environment
manifests:
  kustomize:
    paths:
    - k8s-clean/overlays/prod-namespace
    buildArgs:
    - --load-restrictor=LoadRestrictionsNone
deploy:
  kubectl:
    flags:
      apply: ["--server-side", "--force-conflicts"]
  statusCheck: false  # Disable status checking for namespace
---
apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: webapp-prod-app
# Build section required for image substitution, but build is skipped when image is provided
build:
  artifacts:
  - image: europe-west1-docker.pkg.dev/u2i-tenant-webapp-prod/webapp-images/webapp
manifests:
  kustomize:
    paths:
    - k8s-clean/overlays/production-gateway
    buildArgs:
    - --load-restrictor=LoadRestrictionsNone
deploy:
  kubectl:
    flags:
      apply: ["--server-side", "--force-conflicts"]
  statusCheck: true  # Enable status checking for app resources
---
apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: webapp-prod-kcc
manifests:
  kustomize:
    paths:
    - k8s-clean/kcc/overlays/production-gateway
    buildArgs:
    - --load-restrictor=LoadRestrictionsNone
deploy:
  kubectl:
    flags:
      apply: ["--server-side", "--force-conflicts"]
  statusCheck: false  # Disable status checking for KCC resources