apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: webapp-preview-deployment
build:
  artifacts:
  - image: europe-west1-docker.pkg.dev/u2i-tenant-webapp/webapp-images/webapp
    docker:
      dockerfile: Dockerfile
  googleCloudBuild:
    projectId: u2i-tenant-webapp
    region: europe-west1
  tagPolicy:
    sha256: {}
manifests:
  kustomize:
    paths:
    - k8s-clean/overlays/preview-gateway
    buildArgs:
    - --load-restrictor=LoadRestrictionsNone
deploy:
  kubectl:
    flags:
      apply: ["--wait=true"]
      global: ["--request-timeout=600s"]
  statusCheckDeadlineSeconds: 1200
profiles:
- name: cert-only
  manifests:
    kustomize:
      paths:
      - k8s-clean/overlays/preview-gateway-cert
      buildArgs:
      - --load-restrictor=LoadRestrictionsNone
  deploy:
    kubectl:
      flags:
        apply: ["--wait=true"]
        global: ["--request-timeout=600s"]
  
- name: infra-only
  manifests:
    kustomize:
      paths:
      - k8s-clean/overlays/preview-gateway-infra
      buildArgs:
      - --load-restrictor=LoadRestrictionsNone
  deploy:
    kubectl:
      flags:
        apply: ["--wait=true"]
        global: ["--request-timeout=60s"]

- name: app-only
  manifests:
    kustomize:
      paths:
      - k8s-clean/overlays/preview-gateway
      buildArgs:
      - --load-restrictor=LoadRestrictionsNone
  deploy:
    kubectl:
      flags:
        apply: ["--wait=true"]
        global: ["--request-timeout=300s"]

customActions:
- name: cert-action
  containers:
  - name: run-cert
    image: gcr.io/google.com/cloudsdktool/cloud-sdk:alpine
    command: ["/bin/sh"]
    args:
    - -c
    - |
      echo "Deploying certificate resources..."
      # The manifests are already rendered by Cloud Deploy with parameters substituted
      # We just need to apply them
      kubectl apply -f <(skaffold render -p cert-only) \
        --wait=true \
        --timeout=600s
      echo "Certificate deployment complete"

- name: infra-action  
  containers:
  - name: run-infra
    image: gcr.io/google.com/cloudsdktool/cloud-sdk:alpine
    command: ["/bin/sh"]
    args:
    - -c
    - |
      echo "Deploying infrastructure resources..."
      # The manifests are already rendered by Cloud Deploy with parameters substituted
      kubectl apply -f <(skaffold render -p infra-only) \
        --wait=true \
        --timeout=60s
      echo "Infrastructure deployment complete"