apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: webapp
build:
  artifacts:
  - image: europe-west1-docker.pkg.dev/u2i-tenant-webapp/webapp-images/webapp
    docker:
      dockerfile: Dockerfile
  googleCloudBuild:
    projectId: u2i-tenant-webapp
    region: europe-west1
  tagPolicy:
    gitCommit:
      variant: AbbrevCommitSha
manifests:
  kustomize:
    paths:
    - k8s-clean/overlays/dev
    buildArgs:
    - --load-restrictor=LoadRestrictionsNone
deploy:
  kubectl:
    flags:
      apply: ["--wait=true"]
      global: ["--request-timeout=300s"]

profiles:
# Production profile
- name: prod
  build:
    googleCloudBuild:
      projectId: u2i-tenant-webapp-prod
    tagPolicy:
      gitCommit:
        variant: Tags
  manifests:
    kustomize:
      paths:
      - k8s-clean/overlays/production
  deploy:
    kubectl:
      defaultNamespace: webapp-prod

# Pre-production profile (dev, qa)
- name: preprod
  build:
    tagPolicy:
      gitCommit:
        variant: AbbrevCommitSha
  manifests:
    kustomize:
      paths:
      - k8s-clean/overlays/preprod
  deploy:
    kubectl:
      defaultNamespace: webapp-${NAMESPACE}

# Preview profile for PR deployments
- name: preview
  build:
    tagPolicy:
      sha256: {}
  manifests:
    kustomize:
      paths:
      - k8s-clean/overlays/preview-gateway
      buildArgs:
      - --load-restrictor=LoadRestrictionsNone
  deploy:
    kubectl:
      flags:
        apply: ["--wait=true"]
        global: ["--request-timeout=600s"]
    statusCheckDeadlineSeconds: 1200