apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: webapp-preview
# Single configuration for preview deployments
manifests:
  rawYaml:
  - k8s-clean/namespace/namespace.yaml
  kustomize:
    paths:
    - k8s-clean/overlays/preview-gateway
    buildArgs:
    - --load-restrictor=LoadRestrictionsNone
deploy:
  kubectl:
    flags:
      apply: ["--server-side", "--force-conflicts"]