apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: webapp-preview-deployment
build:
  artifacts:
  - image: europe-west1-docker.pkg.dev/u2i-tenant-webapp/webapp-images/webapp
    docker:
      dockerfile: Dockerfile
  googleCloudBuild:
    projectId: u2i-tenant-webapp
    region: europe-west1
  tagPolicy:
    sha256: {}
manifests:
  kustomize:
    paths:
    - k8s-clean/overlays/preview-gateway
    buildArgs:
    - --load-restrictor=LoadRestrictionsNone
deploy:
  kubectl:
    flags:
      apply: ["--wait=true"]
      global: ["--request-timeout=600s"]
  statusCheckDeadlineSeconds: 1200
profiles:
- name: cert-only
  manifests:
    kustomize:
      paths:
      - k8s-clean/overlays/preview-gateway-cert
      buildArgs:
      - --load-restrictor=LoadRestrictionsNone
  deploy:
    kubectl:
      flags:
        apply: ["--wait=true"]
        global: ["--request-timeout=600s"]
  
- name: infra-only
  manifests:
    kustomize:
      paths:
      - k8s-clean/overlays/preview-gateway-infra
      buildArgs:
      - --load-restrictor=LoadRestrictionsNone
  deploy:
    kubectl:
      flags:
        apply: ["--wait=true"]
        global: ["--request-timeout=60s"]

- name: app-only
  manifests:
    kustomize:
      paths:
      - k8s-clean/overlays/preview-gateway
      buildArgs:
      - --load-restrictor=LoadRestrictionsNone
  deploy:
    kubectl:
      flags:
        apply: ["--wait=true"]
        global: ["--request-timeout=300s"]

customActions:
- name: cert-action
  containers:
  - name: run-cert
    image: gcr.io/k8s-skaffold/skaffold:latest
    command: ["/bin/sh"]
    args:
    - -c
    - |
      skaffold deploy -p cert-only \
        --status-check=false \
        --kube-context=$(kubectl config current-context)
      # Wait for certificate to be ready if needed
      # kubectl wait certificate/${CERT_NAME} \
      #   --namespace=${NAMESPACE} \
      #   --for=condition=Ready \
      #   --timeout=300s || true

- name: infra-action  
  containers:
  - name: run-infra
    image: gcr.io/k8s-skaffold/skaffold:latest
    command: ["/bin/sh"]
    args:
    - -c
    - |
      skaffold deploy -p infra-only \
        --status-check=false \
        --kube-context=$(kubectl config current-context)