apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: webapp-dev-deployment
build:
  artifacts:
  - image: europe-west1-docker.pkg.dev/u2i-tenant-webapp/webapp-images/webapp
    docker:
      dockerfile: Dockerfile
  tagPolicy:
    gitCommit:
      variant: AbbrevCommitSha
manifests:
  kustomize:
    paths:
    - k8s-clean/overlays/dev
profiles:
- name: dev
  manifests:
    kustomize:
      paths:
      - k8s-clean/overlays/dev