apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: webapp-preview-deployment
# No build section - Cloud Build handles building
# No manifests section - Cloud Build handles applying manifests
deploy:
  # Empty deploy section - everything handled by custom action
  kubectl: {}
customActions:
- name: deploy-with-cloud-build
  containers:
  - name: cloud-build-trigger
    image: gcr.io/cloud-builders/gcloud
    command: ["/bin/sh", "-c"]
    args:
    - |
      set -ex
      echo "=== Triggering Cloud Build for full deployment ==="
      
      # Submit Cloud Build with substitutions
      gcloud builds submit \
        --config=cloudbuild-preview-deploy.yaml \
        --project=u2i-tenant-webapp \
        --region=europe-west1 \
        --substitutions="_NAMESPACE=${NAMESPACE},_CERT_NAME=${CERT_NAME},_IMAGE_TAG=${GITHUB_SHA}" \
        .
      
      echo "=== Cloud Build completed successfully ==="
profiles:
# Cloud Build profile - no manifests since everything is handled by Cloud Build
- name: preview-all
  # Empty profile - all deployment handled by Cloud Build custom action