apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: webapp-deployment
build:
  artifacts:
  - image: europe-west1-docker.pkg.dev/u2i-tenant-webapp/webapp-images/webapp
    docker:
      dockerfile: Dockerfile
  googleCloudBuild:
    projectId: u2i-tenant-webapp
    region: europe-west1
manifests:
  kustomize:
    paths:
    - k8s-clean/overlays/nonprod
profiles:
- name: non-prod
  manifests:
    kustomize:
      paths:
      - k8s-clean/overlays/nonprod
- name: prod
  manifests:
    kustomize:
      paths:
      - k8s-clean/overlays/prod