apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: webapp-preview-deployment
build:
  artifacts:
  - image: europe-west1-docker.pkg.dev/u2i-tenant-webapp/webapp-images/webapp
    docker:
      dockerfile: Dockerfile
  googleCloudBuild:
    projectId: u2i-tenant-webapp
    region: europe-west1
  tagPolicy:
    sha256: {}
manifests:
  kustomize:
    paths:
    - k8s-clean/overlays/preview-gateway-cert
    - k8s-clean/overlays/preview-gateway-infra
    - k8s-clean/overlays/preview-gateway
    buildArgs:
    - --load-restrictor=LoadRestrictionsNone
deploy:
  kubectl: {}
customActions:
- name: deploy-preview
  containers:
  - name: cloud-build-trigger
    image: gcr.io/cloud-builders/gcloud
    command: ["/bin/sh", "-c"]
    args:
    - |
      set -ex
      echo "=== Triggering Cloud Build for deployment ==="
      
      # Cloud Build will use rendered.yaml from the current directory
      gcloud builds submit \
        --config=cloudbuild-preview-deploy.yaml \
        --project=u2i-tenant-webapp \
        --region=europe-west1 \
        --substitutions="_NAMESPACE=${NAMESPACE},_CERT_NAME=${CERT_NAME}" \
        . 
      
      echo "=== Cloud Build completed successfully ==="
profiles:
- name: preview-all