apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: webapp-preview-deployment
build:
  artifacts:
  - image: europe-west1-docker.pkg.dev/u2i-tenant-webapp/webapp-images/webapp
    docker:
      dockerfile: Dockerfile
  googleCloudBuild:
    projectId: u2i-tenant-webapp
    region: europe-west1
  tagPolicy:
    sha256: {}
manifests:
  kustomize:
    paths:
    - k8s-clean/overlays/preview-gateway
    buildArgs:
    - --load-restrictor=LoadRestrictionsNone
deploy:
  kubectl:
    flags:
      apply: ["--wait=true"]
      global: ["--request-timeout=600s"]
  statusCheckDeadlineSeconds: 1200
profiles:
# Profile for Config Connector resources (namespace + cert)
- name: config-connector
  manifests:
    kustomize:
      paths:
      - k8s-clean/overlays/preview-gateway-cert
      buildArgs:
      - --load-restrictor=LoadRestrictionsNone
  deploy:
    kubectl:
      flags:
        apply: ["--wait=true", "--server-side"]
        global: ["--request-timeout=600s"]

# Profile for remaining infra + app (includes docker build)
- name: infra-app
  manifests:
    kustomize:
      paths:
      - k8s-clean/overlays/preview-gateway-infra
      - k8s-clean/overlays/preview-gateway
      buildArgs:
      - --load-restrictor=LoadRestrictionsNone
  deploy:
    kubectl:
      flags:
        apply: ["--wait=true"]
        global: ["--request-timeout=300s"]

# Legacy profiles for compatibility
- name: cert-only
  manifests:
    kustomize:
      paths:
      - k8s-clean/overlays/preview-gateway-cert
      buildArgs:
      - --load-restrictor=LoadRestrictionsNone
  deploy:
    kubectl:
      flags:
        apply: ["--wait=true"]
        global: ["--request-timeout=600s"]
  
- name: infra-only
  manifests:
    kustomize:
      paths:
      - k8s-clean/overlays/preview-gateway-infra
      buildArgs:
      - --load-restrictor=LoadRestrictionsNone
  deploy:
    kubectl:
      flags:
        apply: ["--wait=true"]
        global: ["--request-timeout=60s"]

- name: app-only
  manifests:
    kustomize:
      paths:
      - k8s-clean/overlays/preview-gateway
      buildArgs:
      - --load-restrictor=LoadRestrictionsNone
  deploy:
    kubectl:
      flags:
        apply: ["--wait=true"]
        global: ["--request-timeout=300s"]

customActions:
- name: deploy-config-connector
  containers:
  - name: config-connector-deploy
    image: gcr.io/google.com/cloudsdktool/cloud-sdk:alpine
    command: ["/bin/sh"]
    args:
    - -c
    - |
      echo "Deploying Config Connector resources (namespace + cert)..."
      # Apply the pre-rendered config-connector manifests
      kubectl apply -f <(skaffold render -p config-connector) \
        --wait=true \
        --server-side \
        --timeout=600s
      
      # Wait for namespace to be ready
      echo "Waiting for namespace to be ready..."
      kubectl wait namespace/${NAMESPACE} --for=jsonpath='{.status.phase}'=Active --timeout=60s || true
      
      # Note: Certificate readiness is checked by Config Connector itself
      echo "Config Connector deployment complete"