apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: webapp-preview-deployment
build:
  artifacts:
  - image: europe-west1-docker.pkg.dev/u2i-tenant-webapp/webapp-images/webapp
    docker:
      dockerfile: Dockerfile
  googleCloudBuild:
    projectId: u2i-tenant-webapp
    region: europe-west1
  tagPolicy:
    sha256: {}
manifests:
  kustomize:
    paths:
    - k8s-clean/overlays/preview-gateway
    buildArgs:
    - --load-restrictor=LoadRestrictionsNone
customActions:
- name: wait-cert
  containers:
  - name: gcloud-wait
    image: gcr.io/google.com/cloudsdktool/google-cloud-cli:latest
    command: ["/bin/sh"]
    args:
    - -c
    - |
      set -e
      echo "⏳ Waiting for Certificate Manager cert ${CERT_NAME} to become ACTIVE..."
      while true; do
        state=$(gcloud certificate-manager certificates describe "${CERT_NAME}" \
          --project="u2i-tenant-webapp" --location=global \
          --format="value(state)")
        if [ "$state" = "ACTIVE" ]; then
          echo "✅ Certificate is ACTIVE"
          break
        fi
        echo "Current state: $state - waiting 10 seconds..."
        sleep 10
      done