# QA/Production deployment with split app and KCC modules
# Namespace configurations
apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: webapp-namespace
manifests:
  rawYaml:
  - k8s/namespace/namespace.yaml
deploy:
  kubectl:
    flags:
      apply: ["--server-side", "--force-conflicts"]
profiles:
- name: qa
- name: prod
---
# App deployment module (switches between QA and Production based on profile)
apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: webapp-app
build:
  artifacts:
  - image: europe-west1-docker.pkg.dev/u2i-tenant-webapp-nonprod/webapp-images/webapp
manifests:
  kustomize:
    paths:
    - k8s-clean/overlays/qa  # Default to QA
    buildArgs:
    - --load-restrictor=LoadRestrictionsNone
deploy:
  kubectl:
    flags:
      apply: ["--server-side", "--force-conflicts"]
  statusCheck: true  # Enable status checking for app resources
profiles:
- name: qa
  manifests:
    kustomize:
      paths:
      - k8s/app/resources/preprod
      buildArgs:
      - --load-restrictor=LoadRestrictionsNone
- name: prod
  build:
    artifacts:
    - image: europe-west1-docker.pkg.dev/u2i-tenant-webapp-prod/webapp-images/webapp
  manifests:
    kustomize:
      paths:
      - k8s/app/resources/prod
      buildArgs:
      - --load-restrictor=LoadRestrictionsNone
---
# KCC module (switches between QA and Production based on profile)
apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: webapp-kcc
manifests:
  rawYaml:
  - k8s/gcp/certificate.yaml
deploy:
  kubectl:
    flags:
      apply: ["--server-side", "--force-conflicts"]
  statusCheck: false  # Disable status checking for KCC resources
profiles:
- name: qa
- name: prod