apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: webapp-namespace
# Namespace module - creates namespace for both QA and Production environments
manifests:
  rawYaml:
  - k8s-clean/namespace/namespace-nonprod.yaml
deploy:
  kubectl:
    flags:
      apply: ["--server-side", "--force-conflicts"]
profiles:
- name: qa
  # QA namespace configuration - uses nonprod project
- name: prod
  # Production namespace configuration - uses prod project
  manifests:
    rawYaml:
    - k8s-clean/namespace/namespace-prod.yaml
---
apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: webapp-qa-prod-deployment
# Build section required for image substitution, but build is skipped when image is provided
build:
  artifacts:
  - image: europe-west1-docker.pkg.dev/u2i-tenant-webapp-nonprod/webapp-images/webapp
manifests:
  kustomize:
    paths:
    - k8s-clean/overlays/qa-gateway  # Default to QA
    buildArgs:
    - --load-restrictor=LoadRestrictionsNone
deploy:
  kubectl:
    flags:
      apply: ["--server-side", "--force-conflicts"]
profiles:
# QA Profile
- name: qa
  manifests:
    kustomize:
      paths:
      - k8s-clean/overlays/qa-gateway
      buildArgs:
      - --load-restrictor=LoadRestrictionsNone

# Production Profile  
- name: prod
  build:
    artifacts:
    - image: europe-west1-docker.pkg.dev/u2i-tenant-webapp-prod/webapp-images/webapp
      # For prod, we use the prod artifact registry
  manifests:
    kustomize:
      paths:
      - k8s-clean/overlays/production-gateway
      buildArgs:
      - --load-restrictor=LoadRestrictionsNone