apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: webapp-preview-deployment
build:
  artifacts:
  - image: europe-west1-docker.pkg.dev/u2i-tenant-webapp/webapp-images/webapp
    docker:
      dockerfile: Dockerfile
  googleCloudBuild:
    projectId: u2i-tenant-webapp
    region: europe-west1
  tagPolicy:
    sha256: {}
manifests:
  kustomize:
    paths:
    - k8s-clean/overlays/preview-gateway
    buildArgs:
    - --load-restrictor=LoadRestrictionsNone
deploy:
  kubectl:
    flags:
      apply: ["--wait=true", "--server-side", "--timeout=600s"]
      global: ["--request-timeout=600s"]
  statusCheckDeadlineSeconds: 1200
  hooks:
    before:
    - host:
        command: ["sh", "-c"]
        args:
        - |
          echo "=== Starting preDeploy hook for certificate provisioning ==="
          
          # 1️⃣ Create namespace and certificate
          echo "Applying certificate resources..."
          kubectl apply -k k8s-clean/overlays/preview-gateway-cert \
            --wait=true --server-side --timeout=600s
          
          # 2️⃣ Wait for certificate to be ACTIVE
          echo "Waiting for certificate to become ACTIVE..."
          kubectl wait \
            --for=jsonpath='{.status.state}'=ACTIVE \
            --timeout=10m \
            -n ${NAMESPACE} \
            certificatemanagercertificates/${CERT_NAME}
          
          echo "Certificate is ACTIVE!"
          
          # 3️⃣ Apply infrastructure resources
          echo "Applying infrastructure resources..."
          kubectl apply -k k8s-clean/overlays/preview-gateway-infra \
            --wait=true --server-side --timeout=300s
          
          echo "=== PreDeploy hook completed successfully ==="
profiles:
# Single profile - app deployment only (cert and infra handled by preDeploy hook)
- name: preview-all
  manifests:
    kustomize:
      paths:
      # Only the application deployment - cert and infra are handled by the hook
      - k8s-clean/overlays/preview-gateway
      buildArgs:
      - --load-restrictor=LoadRestrictionsNone