# Preview deployment with split app and KCC modules
apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: webapp-namespace
# Namespace module - just renders and deploys namespace
manifests:
  rawYaml:
  - k8s/namespace/namespace.yaml
deploy:
  kubectl:
    flags:
      apply: ["--server-side", "--force-conflicts"]
profiles:
- name: preview-all
---
apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: webapp-preview-app
# Build section required for image substitution, but build is skipped when image is provided
build:
  artifacts:
  - image: europe-west1-docker.pkg.dev/u2i-tenant-webapp-nonprod/webapp-images/webapp
deploy:
  kubectl:
    flags:
      apply: ["--server-side", "--force-conflicts"]
  statusCheck: true  # Enable status checking for app resources
profiles:
- name: preview-all
  manifests:
    kustomize:
      paths:
      - k8s/app/resources/preview
      buildArgs:
      - --load-restrictor=LoadRestrictionsNone
---
apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: webapp-preview-kcc
manifests:
  rawYaml:
  - k8s/gcp/certificate.yaml
deploy:
  kubectl:
    flags:
      apply: ["--server-side", "--force-conflicts"]
  statusCheck: false  # Disable status checking for KCC resources
profiles:
- name: preview-all