apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: webapp-deployment
build:
  artifacts:
  - image: webapp
    docker:
      dockerfile: Dockerfile
manifests:
  rawYaml:
  # Infrastructure manifests (RBAC, quotas, network policies - namespace managed by platform)
  - k8s-infra/rbac.yaml
  - k8s-infra/resource-quota.yaml
  - k8s-infra/network-policy.yaml
  # Application manifests (excluding ingress for now)
  - k8s-manifests/deployment.yaml
  - k8s-manifests/service.yaml
profiles:
- name: nonprod
  manifests:
    rawYaml:
    - k8s-infra/rbac.yaml
    - k8s-infra/resource-quota.yaml
    - k8s-infra/network-policy.yaml
    - k8s-manifests/deployment.yaml
    - k8s-manifests/service.yaml
  patches:
  # Infrastructure patches for nonprod
  - op: replace
    path: /spec/hard/requests.cpu
    value: "2"
    resourceFilter:
      kinds:
      - ResourceQuota
      name: "webapp-team-quota"
  - op: replace
    path: /spec/hard/requests.memory
    value: "4Gi"
    resourceFilter:
      kinds:
      - ResourceQuota
      name: "webapp-team-quota"
  - op: replace
    path: /spec/hard/limits.cpu
    value: "4"
    resourceFilter:
      kinds:
      - ResourceQuota
      name: "webapp-team-quota"
  - op: replace
    path: /spec/hard/limits.memory
    value: "8Gi"
    resourceFilter:
      kinds:
      - ResourceQuota
      name: "webapp-team-quota"
  - op: replace
    path: /spec/hard/pods
    value: "10"
    resourceFilter:
      kinds:
      - ResourceQuota
      name: "webapp-team-quota"
  
  # Application patches for nonprod
  - op: replace
    path: /spec/replicas
    value: 2
    resourceFilter:
      kinds:
      - Deployment
      name: "webapp"
  - op: replace
    path: /spec/template/spec/containers/0/env/1/value
    value: "nonprod"
    resourceFilter:
      kinds:
      - Deployment
      name: "webapp"
# Ingress patches removed for simplified deployment

- name: prod
  manifests:
    rawYaml:
    - k8s-infra/rbac.yaml
    - k8s-infra/resource-quota.yaml
    - k8s-infra/network-policy.yaml
    - k8s-manifests/deployment.yaml
    - k8s-manifests/service.yaml
  patches:
  # Infrastructure patches for prod
  - op: replace
    path: /spec/hard/requests.cpu
    value: "4"
    resourceFilter:
      kinds:
      - ResourceQuota
      name: "webapp-team-quota"
  - op: replace
    path: /spec/hard/requests.memory
    value: "8Gi"
    resourceFilter:
      kinds:
      - ResourceQuota
      name: "webapp-team-quota"
  - op: replace
    path: /spec/hard/limits.cpu
    value: "8"
    resourceFilter:
      kinds:
      - ResourceQuota
      name: "webapp-team-quota"
  - op: replace
    path: /spec/hard/limits.memory
    value: "16Gi"
    resourceFilter:
      kinds:
      - ResourceQuota
      name: "webapp-team-quota"
  - op: replace
    path: /spec/hard/pods
    value: "20"
    resourceFilter:
      kinds:
      - ResourceQuota
      name: "webapp-team-quota"
  
  # Application patches for prod
  - op: replace
    path: /spec/replicas
    value: 3
    resourceFilter:
      kinds:
      - Deployment
      name: "webapp"
  - op: replace
    path: /spec/template/spec/containers/0/env/1/value
    value: "production"
    resourceFilter:
      kinds:
      - Deployment
      name: "webapp"
  - op: replace
    path: /spec/template/spec/containers/0/resources/requests/cpu
    value: "200m"
    resourceFilter:
      kinds:
      - Deployment
      name: "webapp"
  - op: replace
    path: /spec/template/spec/containers/0/resources/requests/memory
    value: "256Mi"
    resourceFilter:
      kinds:
      - Deployment
      name: "webapp"
  - op: replace
    path: /spec/template/spec/containers/0/resources/limits/cpu
    value: "500m"
    resourceFilter:
      kinds:
      - Deployment
      name: "webapp"
  - op: replace
    path: /spec/template/spec/containers/0/resources/limits/memory
    value: "512Mi"
    resourceFilter:
      kinds:
      - Deployment
      name: "webapp"
# Ingress patches removed for simplified deployment