apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: webapp-namespace
# Namespace module - just renders and deploys namespace
manifests:
  rawYaml:
  - k8s-clean/namespace/namespace.yaml
deploy:
  kubectl:
    flags:
      apply: ["--server-side", "--force-conflicts"]
---
apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: webapp-preview-deployment
# No build section - image will be provided by Cloud Deploy
manifests:
  kustomize:
    paths:
    - k8s-clean/overlays/preview-gateway
    buildArgs:
    - --load-restrictor=LoadRestrictionsNone
deploy:
  kubectl:
    flags:
      apply: ["--server-side", "--force-conflicts"]
profiles:
- name: preview-all
  requires:
  - config: webapp-namespace
  - config: webapp-preview-deployment
    # Activate all modules together
    activation:
    - kubeContext: {}