# QA/Production deployment with split app and KCC modules
# Namespace configurations
apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: webapp-namespace
manifests:
  rawYaml:
  - k8s-clean/namespace/namespace-nonprod.yaml
deploy:
  kubectl:
    flags:
      apply: ["--server-side", "--force-conflicts"]
profiles:
- name: prod
  manifests:
    rawYaml:
    - k8s-clean/namespace/namespace-prod.yaml
---
# QA configurations
apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: webapp-qa-app
build:
  artifacts:
  - image: europe-west1-docker.pkg.dev/u2i-tenant-webapp-nonprod/webapp-images/webapp
manifests:
  kustomize:
    paths:
    - k8s-clean/overlays/qa-gateway
    buildArgs:
    - --load-restrictor=LoadRestrictionsNone
deploy:
  kubectl:
    flags:
      apply: ["--server-side", "--force-conflicts"]
  statusCheck: true  # Enable status checking for app resources
profiles:
- name: qa
---
apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: webapp-qa-kcc
manifests:
  kustomize:
    paths:
    - k8s-clean/kcc/overlays/qa-gateway
    buildArgs:
    - --load-restrictor=LoadRestrictionsNone
deploy:
  kubectl:
    flags:
      apply: ["--server-side", "--force-conflicts"]
  statusCheck: false  # Disable status checking for KCC resources
profiles:
- name: qa
---
# Production configurations
apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: webapp-prod-app
build:
  artifacts:
  - image: europe-west1-docker.pkg.dev/u2i-tenant-webapp-prod/webapp-images/webapp
manifests:
  kustomize:
    paths:
    - k8s-clean/overlays/production-gateway
    buildArgs:
    - --load-restrictor=LoadRestrictionsNone
deploy:
  kubectl:
    flags:
      apply: ["--server-side", "--force-conflicts"]
  statusCheck: true  # Enable status checking for app resources
profiles:
- name: prod
---
apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: webapp-prod-kcc
manifests:
  kustomize:
    paths:
    - k8s-clean/kcc/overlays/production-gateway
    buildArgs:
    - --load-restrictor=LoadRestrictionsNone
deploy:
  kubectl:
    flags:
      apply: ["--server-side", "--force-conflicts"]
  statusCheck: false  # Disable status checking for KCC resources
profiles:
- name: prod