apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: webapp-namespace
# Namespace module - creates namespace for production environment
manifests:
  rawYaml:
  - k8s-clean/namespace/namespace.yaml
deploy:
  kubectl:
    flags:
      apply: ["--server-side", "--force-conflicts"]
---
apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: webapp-prod-deployment
# Build section required for image substitution, but build is skipped when image is provided
build:
  artifacts:
  - image: europe-west1-docker.pkg.dev/u2i-tenant-webapp-prod/webapp-images/webapp
manifests:
  kustomize:
    paths:
    - k8s-clean/overlays/production-gateway
    buildArgs:
    - --load-restrictor=LoadRestrictionsNone
deploy:
  kubectl:
    flags:
      apply: ["--server-side", "--force-conflicts"]
profiles:
- name: prod