apiVersion: v1
kind: Pod
metadata:
  name: test-auth
  namespace: webapp-dev
spec:
  serviceAccountName: webapp
  automountServiceAccountToken: true
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
    fsGroup: 2000
  containers:
  - name: gcloud
    image: google/cloud-sdk:alpine
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
    command:
    - sh
    - -c
    - |
      echo "Testing authentication..."
      gcloud auth list
      echo "---"
      echo "Testing AlloyDB connection..."
      gcloud alloydb instances list --cluster=webapp-nonprod-alloydb --region=europe-west1 --project=u2i-tenant-webapp-nonprod
      echo "---"
      echo "Testing IAM permissions..."
      gcloud projects get-iam-policy u2i-tenant-webapp-nonprod --flatten="bindings[].members" --filter="bindings.members:serviceAccount:webapp-k8s@u2i-tenant-webapp-nonprod.iam.gserviceaccount.com"
      echo "---"
      echo "Keeping pod alive for debugging..."
      sleep 3600
    resources:
      requests:
        memory: "128Mi"
        cpu: "50m"
      limits:
        memory: "256Mi"
        cpu: "100m"