steps:
# Run Tests
- name: 'node:18-alpine'
  id: 'run-tests'
  entrypoint: 'sh'
  args:
  - '-c'
  - |
    npm ci
    npm run test:ci
    echo "✅ Tests passed successfully!"

# Report success to GitHub
- name: 'gcr.io/cloud-builders/gcloud'
  id: 'report-status'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    echo "Tests completed successfully"

options:
  logging: CLOUD_LOGGING_ONLY
  
timeout: 300s

substitutions:
  _PR_NUMBER: ${_PR_NUMBER}