# Cloud Build configuration for PR tests with database
# This runs unit and integration tests using Docker Compose

steps:
  # Step 1: Build test image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-test-image'
    args:
      - 'build'
      - '--target'
      - 'test-runner'
      - '-t'
      - 'webapp-test:${BUILD_ID}'
      - '-f'
      - 'Dockerfile.test'
      - '.'

  # Step 2: Run all tests with Docker Compose (includes database)
  - name: 'docker/compose:1.29.2'
    id: 'run-tests-with-db'
    args:
      - '-f'
      - 'docker-compose.ci.yml'
      - 'up'
      - '--abort-on-container-exit'
      - '--exit-code-from'
      - 'app-test'
    env:
      - 'PROJECT_ID=${PROJECT_ID}'
      - 'BUILD_ID=${BUILD_ID}'

  # Step 3: Clean up
  - name: 'docker/compose:1.29.2'
    id: 'cleanup'
    args:
      - '-f'
      - 'docker-compose.ci.yml'
      - 'down'
      - '-v'
    waitFor: ['run-tests-with-db']

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'  # More CPU for faster builds
  
timeout: 600s  # 10 minutes for full test suite

substitutions:
  _PROJECT_ID: u2i-tenant-webapp-nonprod
  _REGION: europe-west1
  _PR_NUMBER: ${_PR_NUMBER}