steps:
# Run Tests
- name: 'node:18-alpine'
  id: 'run-tests'
  entrypoint: 'sh'
  args:
  - '-c'
  - |
    npm ci
    npm run test:ci
    echo "✅ Tests passed successfully!"


options:
  logging: CLOUD_LOGGING_ONLY
  
timeout: 300s

substitutions:
  _PROJECT_ID: u2i-tenant-webapp-nonprod
  _REGION: europe-west1
  _PR_NUMBER: ${_PR_NUMBER}