steps:
# Build the Docker image
- name: 'gcr.io/cloud-builders/docker'
  id: 'build-image'
  args: [
    'build',
    '-t', '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/webapp-images/webapp:preview-${_PR_NUMBER}-${COMMIT_SHA}',
    '-t', '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/webapp-images/webapp:preview-${_PR_NUMBER}-latest',
    '.'
  ]

# Push the Docker image
- name: 'gcr.io/cloud-builders/docker'
  id: 'push-image'
  args: ['push', '--all-tags', '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/webapp-images/webapp']

# Deploy preview environment using compliance-cli
- name: 'us-docker.pkg.dev/u2i-bootstrap/gcr.io/compliance-cli-builder:latest'
  id: 'deploy-preview'
  entrypoint: 'compliance-cli'
  args: ['preview', 'deploy']
  env:
  - 'PROJECT_ID=${_PROJECT_ID}'
  - 'REGION=${_REGION}'
  - 'COMMIT_SHA=$COMMIT_SHA'
  - 'SHORT_SHA=$SHORT_SHA'
  - 'PR_NUMBER=${_PR_NUMBER}'

# Post PR comment with preview URL
- name: 'us-docker.pkg.dev/u2i-bootstrap/gcr.io/compliance-cli-builder:latest'
  id: 'post-pr-comment'
  entrypoint: 'compliance-cli'
  args: ['pr', 'comment', '--pr-number', '${_PR_NUMBER}', '--preview-url', 'https://preview-pr${_PR_NUMBER}.webapp.u2i.dev/']
  env:
  - 'PROJECT_ID=${_PROJECT_ID}'

options:
  logging: CLOUD_LOGGING_ONLY
  
substitutions:
  _PROJECT_ID: u2i-tenant-webapp-nonprod
  _REGION: europe-west1
  _PR_NUMBER: '1'  # Default, will be overridden by trigger