# No secrets needed here - GitHub App auth handled in script

steps:
# Extract PR number from the pull request using pre-built compliance-cli image
- name: 'us-docker.pkg.dev/u2i-bootstrap/gcr.io/compliance-cli-builder:latest'
  id: 'get-pr-number'
  entrypoint: 'bash'
  args: ['-c', 'compliance-cli pr get-number']
  env:
  - '_PR_NUMBER=${_PR_NUMBER}'
  - '_HEAD_BRANCH=${_HEAD_BRANCH}'
  - '_BASE_BRANCH=${_BASE_BRANCH}'

# Build the Docker image
- name: 'gcr.io/cloud-builders/docker'
  id: 'build-image'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    docker build \
      -t ${_REGION}-docker.pkg.dev/${_PROJECT_ID}/webapp-images/webapp:preview-$COMMIT_SHA \
      -t ${_REGION}-docker.pkg.dev/${_PROJECT_ID}/webapp-images/webapp:preview-pr$(cat /workspace/pr_number.txt) \
      .

# Push the Docker image
- name: 'gcr.io/cloud-builders/docker'
  id: 'push-image'
  args: ['push', '--all-tags', '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/webapp-images/webapp']

# Deploy using Cloud Deploy with pre-built compliance-cli image
- name: 'us-docker.pkg.dev/u2i-bootstrap/gcr.io/compliance-cli-builder:latest'
  id: 'deploy-preview'
  entrypoint: 'bash'
  args: ['-c', 'compliance-cli preview']
  env:
  - 'PROJECT_ID=${_PROJECT_ID}'
  - 'REGION=${_REGION}'
  - 'COMMIT_SHA=$COMMIT_SHA'
  - 'SHORT_SHA=$SHORT_SHA'

# Post comment on PR using pre-built compliance-cli image
- name: 'us-docker.pkg.dev/u2i-bootstrap/gcr.io/compliance-cli-builder:latest'
  id: 'post-comment'
  entrypoint: 'bash'
  args: ['-c', 'compliance-cli pr comment']
  env:
  - 'PROJECT_ID=${_PROJECT_ID}'
  - 'REGION=${_REGION}'
  - 'BUILD_ID=$BUILD_ID'

options:
  logging: CLOUD_LOGGING_ONLY
  
substitutions:
  _PROJECT_ID: u2i-tenant-webapp-nonprod
  _REGION: europe-west1