apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  namespace: webapp-team
spec:
  replicas: 3
  template:
    spec:
      containers:
      - name: webapp
        env:
        - name: ENVIRONMENT
          value: "production"
        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"