apiVersion: v1
kind: ResourceQuota
metadata:
  name: webapp-team-quota
  namespace: webapp-team
spec:
  hard:
    requests.cpu: "4"
    requests.memory: "8Gi"
    limits.cpu: "8"
    limits.memory: "16Gi"
    pods: "20"