# Certificate resources for infra-gw namespace
---
# Google-managed certificate for the preview domain
apiVersion: certificatemanager.cnrm.cloud.google.com/v1beta1
kind: CertificateManagerCertificate
metadata:
  name: webapp-preview-cert-preview # from-param: ${CERT_NAME}
  namespace: webapp-dev
  annotations:
    cnrm.cloud.google.com/project-id: u2i-tenant-webapp
spec:
  location: global
  description: Certificate for preview.webapp.u2i.dev # from-param: ${CERT_DESCRIPTION}
  managed:
    domains:
    - preview.webapp.u2i.dev # from-param: ${DOMAIN}

---
# Certificate map entry to associate certificate with the map
apiVersion: certificatemanager.cnrm.cloud.google.com/v1beta1
kind: CertificateManagerCertificateMapEntry  
metadata:
  name: webapp-preview-entry-preview # from-param: ${CERT_ENTRY_NAME}
  namespace: webapp-dev
  annotations:
    cnrm.cloud.google.com/project-id: u2i-tenant-webapp
spec:
  mapRef:
    name: webapp-cert-map
  certificatesRefs:
  - name: preview-webapp-preview-cert-preview # from-param: ${CERT_NAME_WITH_PREFIX}
    namespace: webapp-dev
  hostname: preview.webapp.u2i.dev # from-param: ${DOMAIN}