apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Each resource will have namespace set via Cloud Deploy substitution

resources:
- namespace.yaml
- configconnector-context.yaml
- ../../base/deployment.yaml
- ../../base/service.yaml
- ../../base/network-policy.yaml
- ../../profiles/dev  # Use dev profile for preview resources
- httproute.yaml
- configmap.yaml
- certificate-resources.yaml

# Name prefix can be overridden via --name-prefix
namePrefix: preview-

# Service patch to ensure ClusterIP
patches:
- path: service-patch.yaml
  target:
    kind: Service
    name: webapp-service

# Namespace is added directly to each manifest file

# Common labels for preview deployments
commonLabels:
  stage: preview
  boundary: nonprod
  tier: ephemeral
  tenant: webapp-team
  compliance: iso27001-soc2-gdpr
  data-residency: eu

# Note: ${DOMAIN} and ${PREVIEW_NAME} will be substituted by Cloud Deploy
# at release creation time using --deploy-parameters