apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Single overlay for preview deployments
# Combines all resources needed for preview environment

resources:
# Certificate resources
- certificate-resources.yaml

# Base resources
- ../../base/deployment.yaml
- ../../base/service.yaml
- ../../base/network-policy.yaml

# Gateway routing
- gateway-resources.yaml

# Common labels for all resources - Skaffold will merge with skaffold.dev/run-id
commonLabels:
  app.kubernetes.io/component: webapp