apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Single overlay for preview deployments
# Combines all resources needed for preview environment

resources:
# Namespace
- namespace.yaml

# Certificate resources
- certificate-resources.yaml

# Base resources
- ../../base/deployment.yaml
- ../../base/service.yaml

# Dev profile
- ../../profiles/dev

# Common labels for all resources - Skaffold will merge with skaffold.dev/run-id
commonLabels:
  app.kubernetes.io/component: webapp

# Service patch to ensure ClusterIP
patches:
- path: service-patch.yaml
  target:
    kind: Service
    name: webapp-service