apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Single overlay for preview deployments
# Combines all resources needed for preview environment

resources:
# Namespace
- namespace.yaml

# Certificate resources
- certificate-resources.yaml

# Base resources
- ../../base/deployment.yaml
- ../../base/service.yaml
- ../../base/network-policy.yaml

# Gateway routing
- gateway-resources.yaml

# Dev profile
- ../../profiles/dev

# Service patch to ensure ClusterIP
patches:
- path: service-patch.yaml
  target:
    kind: Service
    name: webapp-service