apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Stage 3: Application deployment
resources:
- ../../base/deployment.yaml
- ../../profiles/dev  # Use dev profile for preview resources

# namePrefix removed - names are handled directly in manifests

# Labels for application resources
labels:
- pairs:
    app.kubernetes.io/component: application
  includeSelectors: false