apiVersion: alloydbomni.dbadmin.goog/v1
kind: DBCluster
metadata:
  name: alloydb-preview
  namespace: ${NAMESPACE} # from-param: ${NAMESPACE}
  labels:
    app: alloydb-omni
    component: database
spec:
  databaseVersion: "16.8.0"
  availability:
    numberOfStandbys: 0  # Explicitly disable HA for single-instance preview
    enableStandbyAsReadReplica: false
  primarySpec:
    adminUser:
      passwordRef:
        name: db-pw-alloydb-preview
    availabilityOptions:
      # Single instance configuration - no HA needed for preview
      livenessProbe: Enabled  # Keep container health checks
      readinessProbe: Enabled
    resources:
      memory: 4Gi
      cpu: 2
      disk: 50Gi
    featureGates:
      enableSimulatedMaintenanceEvents: false
