apiVersion: v1
kind: ConfigMap
metadata:
  name: alloydb-user-auth
  namespace: ${NAMESPACE} # from-param: ${NAMESPACE}
data:
  pg_hba.conf: |
    # TYPE  DATABASE        USER            ADDRESS                 METHOD
    local   all             all                                     trust
    host    all             all             127.0.0.1/32            trust
    host    all             all             ::1/128                 trust
    host    all             all             0.0.0.0/0               md5
---
apiVersion: v1
kind: Secret
metadata:
  name: db-pw-alloydb-preview
  namespace: ${NAMESPACE} # from-param: ${NAMESPACE}
type: Opaque
stringData:
  password: dev-password-123  # This should be replaced with a secure password
