# Reduce minAvailable for non-production environments
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: webapp-pdb
  namespace: ${NAMESPACE} # from-param: ${NAMESPACE}
spec:
  minAvailable: 1