apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Dynamic deployment overlay for preview environments
# No ingress, certificates, or static IPs

namespace: webapp-team

resources:
- ../../base

# Ensure service is NodePort for preview access
patches:
- target:
    kind: Service
    name: webapp-service
  patch: |-
    - op: replace
      path: /spec/type
      value: NodePort

# Dynamic namespace from Cloud Deploy parameters
replacements:
- source:
    kind: ConfigMap
    name: deploy-params
    fieldPath: data.namespace
  targets:
  - select:
      kind: Deployment
    fieldPaths:
    - metadata.namespace
  - select:
      kind: Service
    fieldPaths:
    - metadata.namespace

# Parameters ConfigMap (populated by Cloud Deploy)
configMapGenerator:
- name: deploy-params
  literals:
  - namespace=webapp-team # from-param: ${NAMESPACE}
  - boundary=nonprod # from-param: ${BOUNDARY}
  - stage=dev # from-param: ${STAGE}
  - tier=standard # from-param: ${TIER}
  - mode=production # from-param: ${MODE}