apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Lightweight preview using basic LoadBalancer service
# Fastest public IP option - no ingress/certificates
namespace: webapp-team

resources:
- ../../base

# Convert service to LoadBalancer type
patches:
- target:
    kind: Service
    name: webapp-service
  patch: |-
    - op: replace
      path: /spec/type
      value: LoadBalancer

# Labels for preview environments
labels:
- pairs:
    team: webapp-team
    tier: preview
  includeSelectors: false