apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Single consolidated overlay for preview deployments
# Combines cert, infra, and app resources in one phase

resources:
# Namespace first
- ../preview-gateway-cert/namespace.yaml

# Certificate resources
- ../preview-gateway-cert/certificate-resources.yaml

# Infrastructure resources
- ../../base/service.yaml
- ../../base/network-policy.yaml
- ../preview-gateway-infra/gateway-resources.yaml

# Application resources
- ../../base/deployment.yaml
- ../../profiles/dev

# Service patch from infra overlay
patches:
- path: ../preview-gateway-infra/service-patch.yaml
  target:
    kind: Service
    name: webapp-service