apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Stage 2: Infrastructure resources (configmap, service, network policy, routes)
resources:
- ../preview-gateway/configmap.yaml
- ../preview-gateway/httproute.yaml
- ../../base/service.yaml
- ../../base/network-policy.yaml

# Name prefix can be overridden via --name-prefix
namePrefix: preview-

# Service patch to ensure ClusterIP
patches:
- path: ../preview-gateway/service-patch.yaml
  target:
    kind: Service
    name: webapp-service

# Common labels for preview deployments
commonLabels:
  stage: preview
  boundary: nonprod
  tier: ephemeral
  tenant: webapp-team
  compliance: iso27001-soc2-gdpr
  data-residency: eu