apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Stage 2: Infrastructure resources (configmap, service, network policy, routes)
resources:
- ../../base/service.yaml
- ../../base/network-policy.yaml
- gateway-resources.yaml

# namePrefix removed - names are handled directly in manifests

# Service patch to ensure ClusterIP
patches:
- path: service-patch.yaml
  target:
    kind: Service
    name: webapp-service

# ConfigMap removed - not needed by the app

# Labels for infrastructure resources
labels:
- pairs:
    app.kubernetes.io/component: infrastructure
  includeSelectors: false