apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Stage 2: Infrastructure resources (configmap, service, network policy, routes)
resources:
- ../../base/service.yaml
- ../../base/network-policy.yaml
- gateway-resources.yaml

# namePrefix removed - names are handled directly in manifests

# Service patch to ensure ClusterIP
patches:
- path: service-patch.yaml
  target:
    kind: Service
    name: webapp-service

# Environment config
configMapGenerator:
- name: webapp-env-config
  literals:
    - BOUNDARY=${BOUNDARY} # from-param: ${BOUNDARY}
    - STAGE=${STAGE} # from-param: ${STAGE}
    - API_URL=${API_URL} # from-param: ${API_URL}
    - ENV=${ENV} # from-param: ${ENV}

# Labels removed - labels are applied directly in manifests

# Common labels for all resources
commonLabels:
  app.kubernetes.io/component: infrastructure