apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ${NAMESPACE} # from-param: ${NAMESPACE}

# Stage 3: Application deployment
resources:
- ../../base/deployment.yaml
- ../../profiles/dev  # Use dev profile for preview resources

namePrefix: ${NAME_PREFIX} # from-param: ${NAME_PREFIX}

commonLabels:
  stage: ${STAGE} # from-param: ${STAGE}
  boundary: ${BOUNDARY} # from-param: ${BOUNDARY}
  tier: ${TIER} # from-param: ${TIER}
  environment: ${ENV} # from-param: ${ENV}