# Cleanup old L4 SSL proxy resources
# Apply with: kubectl delete -f cleanup-old-resources.yaml
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeForwardingRule
metadata:
  name: webapp-dev-forwarding
  namespace: webapp-team
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeTargetSSLProxy
metadata:
  name: webapp-dev-ssl-proxy
  namespace: webapp-team
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeBackendService
metadata:
  name: webapp-dev-backend
  namespace: webapp-team
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeHealthCheck
metadata:
  name: webapp-dev-health
  namespace: webapp-team
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeSSLPolicy
metadata:
  name: webapp-ssl-policy
  namespace: webapp-team
---
apiVersion: certificatemanager.cnrm.cloud.google.com/v1beta1
kind: CertificateManagerCertificateMapEntry
metadata:
  name: webapp-dev-entry
  namespace: webapp-team
---
apiVersion: certificatemanager.cnrm.cloud.google.com/v1beta1
kind: CertificateManagerCertificate
metadata:
  name: webapp-dev-cert
  namespace: webapp-team
---
apiVersion: certificatemanager.cnrm.cloud.google.com/v1beta1
kind: CertificateManagerDNSAuthorization
metadata:
  name: webapp-dev-auth
  namespace: webapp-team