apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  namespace: webapp-team
spec:
  replicas: 2
  template:
    spec:
      containers:
      - name: webapp
        image: europe-west1-docker.pkg.dev/u2i-tenant-webapp/webapp-images/webapp:v1.0.0
        env:
        - name: ENVIRONMENT
          value: "nonprod"