apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: webapp-team

resources:
- ../../base
- config-connector-resources.yaml

patches:
- target:
    kind: Deployment
    name: webapp
  patch: |-
    - op: replace
      path: /spec/replicas
      value: 2
    - op: replace
      path: /spec/template/spec/containers/0/env/1/value
      value: nonprod

configMapGenerator:
- name: webapp-config
  literals:
    - BOUNDARY=nonprod
    - LOG_LEVEL=debug