apiVersion: v1
kind: Namespace
metadata:
  name: webapp-dev
  labels:
    stage: dev
    boundary: nonprod
    team: webapp-team
    compliance: iso27001-soc2-gdpr
---
apiVersion: v1
kind: Namespace
metadata:
  name: webapp-qa
  labels:
    stage: qa
    boundary: nonprod
    team: webapp-team
    compliance: iso27001-soc2-gdpr
---
apiVersion: v1
kind: Namespace
metadata:
  name: webapp-prod
  labels:
    stage: prod
    boundary: prod
    team: webapp-team
    compliance: iso27001-soc2-gdpr
    critical: "true"