apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  namespace: webapp-team
spec:
  replicas: 2
  template:
    spec:
      containers:
      - name: webapp
        env:
        - name: ENVIRONMENT
          value: "nonprod"