---
# ClusterSecretStore for Google Secret Manager
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: gcp-secret-manager
spec:
  provider:
    gcpsm:
      projectID: u2i-tenant-webapp-nonprod
      auth:
        workloadIdentity:
          clusterLocation: europe-west1
          clusterName: webapp-cluster
          clusterProjectID: u2i-tenant-webapp-nonprod
          serviceAccountRef:
            name: webapp