# Modular Skaffold configuration for preview deployments
# Separates Config Connector resources to avoid status checking bug
# See: https://github.com/GoogleContainerTools/skaffold/issues/7207

apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: preview-namespace
# Module 1: Create namespace for preview environment
manifests:
  rawYaml:
  - ../k8s/namespace/namespace.yml
deploy:
  kubectl:
    flags:
      apply: ["--server-side", "--force-conflicts"]

---
apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: preview-certificates
# Module 2: Deploy Config Connector resources (certificates)
# Status checking disabled to avoid Skaffold bug with Config Connector
requires:
- configs: ["preview-namespace"]
manifests:
  rawYaml:
  - ../k8s/gcp/certificate.yml
deploy:
  kubectl:
    flags:
      apply: ["--server-side", "--force-conflicts"]
  statusCheck: false  # Disabled due to Skaffold Config Connector bug

---
apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: preview-application
# Module 3: Deploy application resources with status checking
requires:
- configs: ["preview-namespace"]
manifests:
  kustomize:
    paths:
    - ../k8s/app/resources/preview
    buildArgs:
    - --load-restrictor=LoadRestrictionsNone
deploy:
  kubectl:
    flags:
      apply: ["--server-side", "--force-conflicts"]
  statusCheck: true
  statusCheckDeadlineSeconds: 300