apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: webapp-team

resources:
- ../../base
- config-connector-resources.yaml

# Note: Profile selection happens at the Cloud Deploy level
# by including the appropriate profile overlay in the skaffold.yaml