# Certificate resources for production environment
---
apiVersion: certificatemanager.cnrm.cloud.google.com/v1beta1
kind: CertificateManagerCertificate
metadata:
  name: ${CERT_NAME} # from-param: ${CERT_NAME}
  namespace: config-control
spec:
  projectRef:
    external: u2i-tenant-webapp-prod
  location: global
  description: ${CERT_DESCRIPTION} # from-param: ${CERT_DESCRIPTION}
  managed:
    domains:
    - ${DOMAIN} # from-param: ${DOMAIN}
    - www.${DOMAIN} # from-param: ${DOMAIN}
---
apiVersion: certificatemanager.cnrm.cloud.google.com/v1beta1
kind: CertificateManagerCertificateMapEntry
metadata:
  name: ${CERT_ENTRY_NAME} # from-param: ${CERT_ENTRY_NAME}
  namespace: config-control
spec:
  projectRef:
    external: u2i-tenant-webapp-prod
  location: global
  description: Certificate map entry for ${DOMAIN} # from-param: ${DOMAIN}
  mapRef:
    name: webapp-cert-map
  hostname: ${DOMAIN} # from-param: ${DOMAIN}
  certificatesRefs:
  - name: ${CERT_NAME} # from-param: ${CERT_NAME}
---
# Entry for www subdomain
apiVersion: certificatemanager.cnrm.cloud.google.com/v1beta1
kind: CertificateManagerCertificateMapEntry
metadata:
  name: ${CERT_ENTRY_NAME}-www # from-param: ${CERT_ENTRY_NAME}
  namespace: config-control
spec:
  projectRef:
    external: u2i-tenant-webapp-prod
  location: global
  description: Certificate map entry for www.${DOMAIN} # from-param: ${DOMAIN}
  mapRef:
    name: webapp-cert-map
  hostname: www.${DOMAIN} # from-param: ${DOMAIN}
  certificatesRefs:
  - name: ${CERT_NAME} # from-param: ${CERT_NAME}