apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Dev profile - small resources for development/testing environments

patches:
- target:
    kind: Deployment
    name: webapp
  patch: |-
    - op: replace
      path: /spec/replicas
      value: 1
    - op: replace
      path: /spec/template/spec/containers/0/resources
      value:
        requests:
          memory: "64Mi"
          cpu: "50m"
        limits:
          memory: "128Mi"
          cpu: "100m"

# Dev-friendly pod disruption budget
resources:
- pod-disruption-budget.yaml

configMapGenerator:
- name: webapp-profile-config
  literals:
    - PROFILE=dev
    - LOG_LEVEL=debug
    - GRACEFUL_SHUTDOWN_TIMEOUT=5s