apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Production environment with Gateway API
# Single stage deployment

resources:
# Certificate resources
- certificate-resources.yaml

# Base resources
- ../../base/deployment.yaml
- ../../base/service.yaml
- ../../base/network-policy.yaml

# Gateway routing
- gateway-resources.yaml

# Production-specific resources
- ../../base/pod-disruption-budget.yaml

# Common labels for all resources
commonLabels:
  app.kubernetes.io/component: webapp
  environment: prod
  compliance: iso27001-soc2-gdpr
  data-residency: eu

# Note: Replica count is set via patches since base uses parameterized names

# Patches
patchesStrategicMerge:
- replicas-patch.yaml