apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ${NAMESPACE} # from-param: ${NAMESPACE}

# Stage 2: Infrastructure resources (configmap, service, network policy, routes)
resources:
- ../../base/service.yaml
- ../../base/network-policy.yaml
- ../production/gateway-resources.yaml

# Environment config
configMapGenerator:
- name: webapp-env-config
  literals:
    - BOUNDARY=${BOUNDARY} # from-param: ${BOUNDARY}
    - STAGE=${STAGE} # from-param: ${STAGE}
    - API_URL=${API_URL} # from-param: ${API_URL}
    - ENV=${ENV} # from-param: ${ENV}

commonLabels:
  stage: ${STAGE} # from-param: ${STAGE}
  boundary: ${BOUNDARY} # from-param: ${BOUNDARY}
  tier: ${TIER} # from-param: ${TIER}
  environment: ${ENV} # from-param: ${ENV}