apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Dev environment with Gateway API
# Single stage deployment

resources:
# Base resources
- ../../base/deployment.yaml
- ../../base/service.yaml
- ../../base/network-policy.yaml

# Gateway routing
- gateway-resources.yaml

# Common labels for all resources
commonLabels:
  app.kubernetes.io/component: webapp
  environment: dev