apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# KCC resources for dev environment
# These are deployed with statusCheck disabled to avoid Skaffold bug #7207
# All values come from Cloud Deploy parameters - no patches needed

resources:
# Use base certificate template with parameters
- ../../../base/certificate-template.yaml

# Common labels for all KCC resources
commonLabels:
  app.kubernetes.io/component: webapp
  environment: dev