apiVersion: v1
kind: Service
metadata:
  name: alloydb-omni
  namespace: ${NAMESPACE} # from-param: ${NAMESPACE}
  labels:
    app: alloydb-omni
    component: database
spec:
  ports:
  - port: 5432
    targetPort: 5432
    name: postgres
  selector:
    app: alloydb-omni
  type: ClusterIP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: alloydb-omni
  namespace: ${NAMESPACE} # from-param: ${NAMESPACE}
  labels:
    app: alloydb-omni
    component: database
spec:
  serviceName: alloydb-omni
  replicas: 1
  selector:
    matchLabels:
      app: alloydb-omni
  template:
    metadata:
      labels:
        app: alloydb-omni
        component: database
    spec:
      securityContext:
        fsGroup: 70
        runAsNonRoot: true
      containers:
      - name: alloydb-omni
        image: gcr.io/alloydb-omni/alloydbomni:16
        ports:
        - containerPort: 5432
          name: postgres
        env:
        - name: POSTGRES_DB
          value: webapp_preview
        - name: POSTGRES_USER
          value: webapp
        - name: POSTGRES_PASSWORD
          value: preview_temp_password
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        - name: ALLOYDB_OMNI_ACCEPT_TERMS
          value: "YES"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/data
        livenessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - webapp
            - -d
            - webapp_preview
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - webapp
            - -d
            - webapp_preview
          initialDelaySeconds: 30
          periodSeconds: 5
          timeoutSeconds: 3
        securityContext:
          runAsUser: 70
          runAsGroup: 70
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          capabilities:
            drop:
            - ALL
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 5Gi