apiVersion: v1
kind: Secret
metadata:
  name: db-pw-alloydb-preview
  namespace: ${NAMESPACE} # from-param: ${NAMESPACE}
type: Opaque
data:
  alloydb-preview: cHJldmlld190ZW1wX3Bhc3N3b3Jk # base64 of "preview_temp_password"
---
apiVersion: alloydbomni.dbadmin.goog/v1
kind: DBCluster
metadata:
  name: alloydb-preview
  namespace: ${NAMESPACE} # from-param: ${NAMESPACE}
  labels:
    app: alloydb-omni
    component: database
spec:
  databaseVersion: "16.8.0"
  availability:
    numberOfStandbys: 0  # Explicitly disable HA for single-instance preview
    enableStandbyAsReadReplica: false
  primarySpec:
    adminUser:
      passwordRef:
        name: db-pw-alloydb-preview
    availabilityOptions:
      # Single instance configuration - no HA needed for preview
      livenessProbe: Enabled  # Keep container health checks
    services:
      # Disable optional services for minimal preview environment
      Logging: false     # Disable logging agent to reduce overhead
      Monitoring: false  # Disable monitoring agent to reduce overhead
    resources:
      cpu: 250m      # Reduced CPU for single instance
      memory: 4Gi    # Minimum memory to avoid OOM
      disks:
      - name: DataDisk
        size: 5Gi
