# UserDefinedAuthentication for AlloyDB Omni preview environments
# Configures pg_hba.conf to allow connections from cluster network
apiVersion: alloydbomni.dbadmin.goog/v1
kind: UserDefinedAuthentication
metadata:
  name: alloydb-preview-auth
  namespace: ${NAMESPACE} # from-param: ${NAMESPACE}
spec:
  dbclusterRef:
    name: alloydb-preview
  pgHbaEntries: |
    # Allow local connections
    local   all             all                                     trust
    # Allow connections from localhost  
    host    all             all             127.0.0.1/32            trust
    host    all             all             ::1/128                 trust
    # Allow connections from cluster network without SSL (for preview)
    host    all             all             10.0.0.0/8              md5
    # Allow SSL connections from anywhere else
    hostssl all             all             0.0.0.0/0               md5
    hostssl all             all             ::/0                    md5