apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Preview profile - small resources for PR preview environments with separate database

resources:
- ../../base
- ../../../namespace/namespace.yml
- ../../../gcp/certificate.yml
- alloydb-omni.yml

patches:
# Adjust resources and configuration for preview
- target:
    kind: Deployment
    labelSelector: "app=webapp"  # Use label selector to match any name
  patch: |-
    - op: replace
      path: /spec/replicas
      value: 1
    - op: remove
      path: /spec/template/spec/initContainers/0  # Remove AlloyDB proxy for preview
    - op: replace
      path: /spec/template/spec/containers/0/resources
      value:
        requests:
          memory: "128Mi"
          cpu: "50m"
        limits:
          memory: "256Mi"
          cpu: "200m"
    - op: add
      path: /spec/template/spec/containers/0/env/-
      value:
        name: DATABASE_HOST
        value: alloydb-omni
    - op: add
      path: /spec/template/spec/containers/0/env/-
      value:
        name: DATABASE_PORT
        value: "5432"
    - op: add
      path: /spec/template/spec/containers/0/env/-
      value:
        name: DATABASE_NAME
        value: webapp_preview
    - op: add
      path: /spec/template/spec/containers/0/env/-
      value:
        name: DATABASE_USER
        value: webapp
    - op: add
      path: /spec/template/spec/containers/0/env/-
      value:
        name: DATABASE_PASSWORD
        value: preview_temp_password
    - op: add
      path: /spec/template/spec/containers/0/env/-
      value:
        name: DATABASE_SSL_MODE
        value: disable
    - op: add
      path: /spec/template/spec/containers/0/env/-
      value:
        name: RUN_MIGRATIONS_ON_STARTUP
        value: "false"  # Migration job will handle this

# Patch migration job to remove AlloyDB proxy and connect directly to AlloyDB Omni
- target:
    kind: Job
    name: webapp-migration
  patch: |-
    - op: remove
      path: /spec/template/spec/initContainers/0  # Remove AlloyDB proxy
    - op: add
      path: /spec/template/spec/containers/0/env/-
      value:
        name: DATABASE_HOST
        value: alloydb-omni
    - op: add
      path: /spec/template/spec/containers/0/env/-
      value:
        name: DATABASE_PORT
        value: "5432"
    - op: add
      path: /spec/template/spec/containers/0/env/-
      value:
        name: DATABASE_NAME
        value: webapp_preview
    - op: add
      path: /spec/template/spec/containers/0/env/-
      value:
        name: DATABASE_USER
        value: webapp
    - op: add
      path: /spec/template/spec/containers/0/env/-
      value:
        name: DATABASE_PASSWORD
        value: preview_temp_password
    - op: add
      path: /spec/template/spec/containers/0/env/-
      value:
        name: DATABASE_SSL_MODE
        value: disable
    - op: replace
      path: /spec/template/spec/containers/0/env/3/value
      value: "false"  # ALLOYDB_AUTH_PROXY = false

configMapGenerator:
- name: webapp-profile-config
  literals:
    - PROFILE=preview
    - LOG_LEVEL=debug
    - GRACEFUL_SHUTDOWN_TIMEOUT=5s