apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Preview profile - small resources for PR preview environments

resources:
- ../../base
- ../../../namespace/namespace.yml
- ../../../gcp/certificate.yml

# Note: AlloyDB Omni component preserved but not used
# Preview environments now use shared AlloyDB with PR-specific databases
# To re-enable AlloyDB Omni, uncomment:
# components:
# - ../../../components/database/alloydb-omni
# resources:
# - db-password-secret.yml

patchesStrategicMerge:
- namespace-patch.yml

patches:
# Adjust resources and configuration
- target:
    kind: Deployment
    labelSelector: "app=webapp"  # Use label selector to match any name
  patch: |-
    - op: replace
      path: /spec/replicas
      value: 1
    - op: replace
      path: /spec/template/spec/initContainers/0/args
      value:
      - "projects/u2i-tenant-webapp-nonprod/locations/europe-west1/clusters/webapp-nonprod-alloydb/instances/webapp-nonprod-alloydb-primary"
      - "--port=5432"
      - "--auto-iam-authn"
    - op: replace
      path: /spec/template/spec/containers/0/resources
      value:
        requests:
          memory: "128Mi"
          cpu: "50m"
        limits:
          memory: "256Mi"
          cpu: "200m"


# Patch migration job to use shared AlloyDB with PR-specific database
- target:
    kind: Job
    name: webapp-migration
  patch: |-
    - op: replace
      path: /spec/template/spec/initContainers/0/args
      value:
      - "projects/u2i-tenant-webapp-nonprod/locations/europe-west1/clusters/webapp-nonprod-alloydb/instances/webapp-nonprod-alloydb-primary"
      - "--port=5432"
      - "--max-connections=10"
      - "--auto-iam-authn"
    - op: replace
      path: /spec/template/spec/containers/0/env/2/value  # Update STAGE value
      value: preview

configMapGenerator:
- name: webapp-profile-config
  literals:
    - PROFILE=preview
    - LOG_LEVEL=debug
    - GRACEFUL_SHUTDOWN_TIMEOUT=5s

# Add AlloyDB network egress for preview environments
- target:
    kind: NetworkPolicy
    name: webapp-network-policy
  patch: |-
    - op: add
      path: /spec/egress/-
      value:
        ports:
        - port: 5433
          protocol: TCP
        - port: 5432
          protocol: TCP
        to:
        - ipBlock:
            cidr: 10.152.0.0/24

# External Secrets configuration will be added as a separate resource file