apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Preview profile - small resources for PR preview environments

resources:
- ../../base
- ../../../namespace/namespace.yml
- ../../../gcp/certificate.yml

patches:
# Remove init containers and adjust resources
- target:
    kind: Deployment
    name: webapp
  patch: |-
    - op: replace
      path: /spec/replicas
      value: 1
    - op: replace
      path: /spec/template/spec/containers/0/resources
      value:
        requests:
          memory: "64Mi"
          cpu: "50m"
        limits:
          memory: "128Mi"
          cpu: "100m"
    - op: remove
      path: /spec/template/spec/initContainers
    - op: add
      path: /spec/template/spec/containers/0/envFrom/-
      value:
        configMapRef:
          name: webapp-preview-postgres-config

# Add PostgreSQL sidecar container using strategic merge
- target:
    kind: Deployment
    name: webapp
  patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: webapp
    spec:
      template:
        spec:
          containers:
          - name: postgres
            image: postgres:15-alpine
            env:
            - name: POSTGRES_DB
              value: webapp_preview
            - name: POSTGRES_USER
              value: webapp
            - name: POSTGRES_PASSWORD
              value: preview_temp_password
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
            ports:
            - containerPort: 5432
              name: postgres
            resources:
              requests:
                memory: "128Mi"
                cpu: "100m"
              limits:
                memory: "256Mi"
                cpu: "200m"
            volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
            securityContext:
              runAsUser: 999
              runAsGroup: 999
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
              capabilities:
                drop:
                - ALL
          volumes:
          - name: postgres-storage
            emptyDir: {}

configMapGenerator:
- name: webapp-profile-config
  literals:
    - PROFILE=preview
    - LOG_LEVEL=debug
    - GRACEFUL_SHUTDOWN_TIMEOUT=5s
- name: webapp-preview-postgres-config
  literals:
    - DATABASE_HOST=localhost
    - DATABASE_PORT=5432
    - DATABASE_NAME=webapp_preview
    - DATABASE_USER=webapp
    - DATABASE_PASSWORD=preview_temp_password
    - RUN_MIGRATIONS_ON_STARTUP=true