apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Preview profile - small resources for PR preview environments

resources:
- ../../base
- ../../../namespace/namespace.yml
- ../../../gcp/certificate.yml

patches:
# Adjust resources and configuration
- target:
    kind: Deployment
    labelSelector: "app=webapp"  # Use label selector to match any name
  patch: |-
    - op: replace
      path: /spec/replicas
      value: 1
    - op: remove
      path: /spec/template/spec/initContainers/0  # Remove AlloyDB proxy for preview
    - op: replace
      path: /spec/template/spec/containers/0/resources
      value:
        requests:
          memory: "128Mi"
          cpu: "50m"
        limits:
          memory: "256Mi"
          cpu: "200m"
    - op: add
      path: /spec/template/spec/containers/0/env/-
      value:
        name: DATABASE_HOST
        value: localhost
    - op: add
      path: /spec/template/spec/containers/0/env/-
      value:
        name: DATABASE_PORT
        value: "5432"
    - op: add
      path: /spec/template/spec/containers/0/env/-
      value:
        name: DATABASE_NAME
        value: webapp_preview
    - op: add
      path: /spec/template/spec/containers/0/env/-
      value:
        name: DATABASE_USER
        value: webapp
    - op: add
      path: /spec/template/spec/containers/0/env/-
      value:
        name: DATABASE_PASSWORD
        value: preview_temp_password
    - op: add
      path: /spec/template/spec/containers/0/env/-
      value:
        name: DATABASE_SSL_MODE
        value: disable

# Add AlloyDB Omni sidecar using JSON6902 patch
- target:
    group: apps
    version: v1
    kind: Deployment
    labelSelector: "app=webapp"  # Use label selector to match any name
  patch: |-
    - op: add
      path: /spec/template/spec/containers/1
      value:
        name: alloydb-omni
        image: gcr.io/alloydb-omni/pg15:latest
        env:
        - name: POSTGRES_DB
          value: webapp_preview
        - name: POSTGRES_USER
          value: webapp
        - name: POSTGRES_PASSWORD
          value: preview_temp_password
        - name: PGDATA
          value: /var/lib/postgresql/data
        - name: ALLOYDB_OMNI_ACCEPT_TERMS
          value: "YES"
        ports:
        - containerPort: 5432
          name: postgres
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        volumeMounts:
        - name: alloydb-storage
          mountPath: /var/lib/postgresql/data
        livenessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - webapp
            - -d
            - webapp_preview
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - webapp
            - -d
            - webapp_preview
          initialDelaySeconds: 30
          periodSeconds: 5
          timeoutSeconds: 3
        securityContext:
          runAsUser: 999
          runAsGroup: 999
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          capabilities:
            drop:
            - ALL
    - op: add
      path: /spec/template/spec/volumes/-
      value:
        name: alloydb-storage
        emptyDir: {}

configMapGenerator:
- name: webapp-profile-config
  literals:
    - PROFILE=preview
    - LOG_LEVEL=debug
    - GRACEFUL_SHUTDOWN_TIMEOUT=5s

# External Secrets configuration will be added as a separate resource file