apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Preview profile - small resources for PR preview environments

resources:
- ../../base
- ../../../namespace/namespace.yml
- ../../../gcp/certificate.yml
- alloydb-omni.yml

patches:
# Relax pod security for AlloyDB Omni operator - use strategic merge patch
- target:
    kind: Namespace
    name: ${NAMESPACE}
  patch: |-
    apiVersion: v1
    kind: Namespace
    metadata:
      name: ${NAMESPACE}
      labels:
        pod-security.kubernetes.io/enforce: baseline
        pod-security.kubernetes.io/audit: baseline
        pod-security.kubernetes.io/warn: baseline
# Adjust resources and configuration
- target:
    kind: Deployment
    labelSelector: "app=webapp"  # Use label selector to match any name
  patch: |-
    - op: replace
      path: /spec/replicas
      value: 1
    - op: remove
      path: /spec/template/spec/initContainers/0  # Remove AlloyDB proxy for preview
    - op: replace
      path: /spec/template/spec/containers/0/resources
      value:
        requests:
          memory: "128Mi"
          cpu: "50m"
        limits:
          memory: "256Mi"
          cpu: "200m"
    - op: add
      path: /spec/template/spec/containers/0/env/-
      value:
        name: DATABASE_HOST
        value: al-alloydb-preview-rw-ilb
    - op: add
      path: /spec/template/spec/containers/0/env/-
      value:
        name: DATABASE_PORT
        value: "5432"
    - op: add
      path: /spec/template/spec/containers/0/env/-
      value:
        name: DATABASE_NAME
        value: webapp_preview
    - op: add
      path: /spec/template/spec/containers/0/env/-
      value:
        name: DATABASE_USER
        value: postgres
    - op: add
      path: /spec/template/spec/containers/0/env/-
      value:
        name: DATABASE_PASSWORD
        value: preview_temp_password
    - op: add
      path: /spec/template/spec/containers/0/env/-
      value:
        name: DATABASE_SSL_MODE
        value: disable


configMapGenerator:
- name: webapp-profile-config
  literals:
    - PROFILE=preview
    - LOG_LEVEL=debug
    - GRACEFUL_SHUTDOWN_TIMEOUT=5s

# External Secrets configuration will be added as a separate resource file