apiVersion: v1
kind: ConfigMap
metadata:
  name: webapp-neon-db-config
data:
  DATABASE_HOST: "localhost"
  DATABASE_PORT: "5432"
  DATABASE_NAME: "webapp_preview"
  DATABASE_USER: "webapp"
  DATABASE_PASSWORD: "preview_temp_password"
  RUN_MIGRATIONS_ON_STARTUP: "true"  # Tell app to run migrations
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  template:
    spec:
      # Remove init container for preview
      initContainers: []
      containers:
      # Add PostgreSQL as a sidecar container
      - name: postgres
        image: postgres:15-alpine
        env:
        - name: POSTGRES_DB
          value: webapp_preview
        - name: POSTGRES_USER
          value: webapp
        - name: POSTGRES_PASSWORD
          value: preview_temp_password
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        ports:
        - containerPort: 5432
          name: postgres
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
        securityContext:
          runAsUser: 999  # postgres user
          runAsGroup: 999
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          capabilities:
            drop:
            - ALL
      volumes:
      - name: postgres-storage
        emptyDir: {}