---
# SecretStore for Google Secret Manager (namespace-specific)
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: gcp-secret-manager
spec:
  provider:
    gcpsm:
      projectID: u2i-tenant-webapp-nonprod
      auth:
        workloadIdentity:
          clusterLocation: europe-west1
          clusterName: webapp-cluster
          clusterProjectID: u2i-tenant-webapp-nonprod
          serviceAccountRef:
            name: webapp
---
# ExternalSecret to sync real secret from Google Secret Manager
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: webapp-demo-external-secret
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: gcp-secret-manager
    kind: SecretStore
  target:
    name: webapp-demo-secret
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
  - secretKey: webapp-demo-secret
    remoteRef:
      key: webapp-demo-secret
      version: latest