apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Production environment with Gateway API
# Single stage deployment

resources:
# Use base kustomization which includes all base resources
- ../../base

# Production-specific resources
- ../../base/pod-disruption-budget.yaml

# Common labels for all resources
# Environment-specific labels only (core labels come from base)
labels:
- pairs:
    environment: prod
  includeSelectors: false