apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Preprod profile - medium resources for dev/qa environments

patches:
- target:
    kind: Deployment
    name: webapp
  patch: |-
    - op: replace
      path: /spec/replicas
      value: 1
    - op: replace
      path: /spec/template/spec/containers/0/resources
      value:
        requests:
          memory: "64Mi"
          cpu: "50m"
        limits:
          memory: "128Mi"
          cpu: "100m"

configMapGenerator:
- name: webapp-profile-config
  literals:
    - PROFILE=preprod
    - LOG_LEVEL=debug
    - GRACEFUL_SHUTDOWN_TIMEOUT=5s