apiVersion: batch/v1
kind: Job
metadata:
  name: webapp-migration
  namespace: webapp-dev # from-param: ${NAMESPACE}
  labels:
    app: webapp
    component: migration
spec:
  ttlSecondsAfterFinished: 3600 # Clean up after 1 hour
  backoffLimit: 3
  template:
    metadata:
      labels:
        app: webapp
        component: migration
    spec:
      serviceAccountName: webapp
      automountServiceAccountToken: true
      restartPolicy: Never
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 2000
      initContainers:
      # AlloyDB Auth Proxy sidecar (runs as init container with restartPolicy: Always)
      - name: alloydb-auth-proxy
        image: gcr.io/alloydb-connectors/alloydb-auth-proxy:latest
        restartPolicy: Always  # This makes it a sidecar
        args:
        - "projects/u2i-tenant-webapp-nonprod/locations/europe-west1/clusters/webapp-nonprod-alloydb/instances/webapp-nonprod-alloydb-primary"
        - "--port=5432"
        - "--max-connections=10"
        - "--auto-iam-authn"
        startupProbe:
          exec:
            command:
            - sh
            - -c
            - "nc -z localhost 5432"
          initialDelaySeconds: 5
          periodSeconds: 2
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 30
        securityContext:
          runAsNonRoot: true
          runAsUser: 2000
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        resources:
          requests:
            memory: "32Mi"
            cpu: "10m"
          limits:
            memory: "64Mi"
            cpu: "100m"
      containers:
      - name: migrate
        image: europe-west1-docker.pkg.dev/u2i-tenant-webapp-nonprod/webapp-images/webapp
        command: ["node", "migrate.js"]
        env:
        - name: PROJECT_ID
          value: "u2i-tenant-webapp-nonprod" # from-param: ${PROJECT_ID}
        - name: BOUNDARY
          value: "nonprod" # from-param: ${BOUNDARY}
        - name: STAGE
          value: "dev" # from-param: ${STAGE}
        - name: ALLOYDB_AUTH_PROXY
          value: "true"
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
