apiVersion: batch/v1
kind: Job
metadata:
  name: webapp-migrate-${SHORT_SHA} # Unique name per deployment
  namespace: ${NAMESPACE}
  labels:
    app: webapp
    component: migration
    version: ${SHORT_SHA}
spec:
  ttlSecondsAfterFinished: 3600 # Clean up after 1 hour
  backoffLimit: 3
  template:
    metadata:
      labels:
        app: webapp
        component: migration
    spec:
      serviceAccountName: webapp
      automountServiceAccountToken: true
      restartPolicy: Never
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 2000
      initContainers:
      # Fetch AlloyDB instance URI from Secret Manager
      - name: fetch-instance-uri
        image: gcr.io/google.com/cloudsdktool/cloud-sdk:alpine
        command:
        - sh
        - -c
        - |
          echo "Fetching AlloyDB instance URI from Secret Manager..."
          # Use webapp-nonprod for all non-prod environments (dev, qa, preview)
          SECRET_NAME="webapp-nonprod-alloydb-instance-uri"
          echo "Fetching secret: $SECRET_NAME from project u2i-tenant-webapp-nonprod"
          
          # The pod uses Workload Identity, so no explicit auth needed
          # Just ensure we're using the metadata server for auth
          gcloud secrets versions access latest \
            --secret="$SECRET_NAME" \
            --project="u2i-tenant-webapp-nonprod" > /shared/instance-uri
          
          if [ $? -eq 0 ]; then
            echo "Instance URI fetched successfully"
            cat /shared/instance-uri
          else
            echo "Failed to fetch instance URI"
            exit 1
          fi
        volumeMounts:
        - name: shared-data
          mountPath: /shared
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 1000
          capabilities:
            drop:
            - ALL
      containers:
      # AlloyDB Auth Proxy sidecar with IAM authentication
      - name: alloydb-auth-proxy
        image: gcr.io/alloydb-connectors/alloydb-auth-proxy:latest
        command:
        - sh
        - -c
        - |
          INSTANCE_URI=$(cat /shared/instance-uri)
          echo "Starting AlloyDB Auth Proxy for instance: $INSTANCE_URI"
          /alloydb-auth-proxy \
            --port=5432 \
            --instances="$INSTANCE_URI=tcp:5432" \
            --max-connections=10 \
            --private-ip \
            --auto-iam-authn
        volumeMounts:
        - name: shared-data
          mountPath: /shared
        securityContext:
          runAsNonRoot: true
          runAsUser: 2000
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        resources:
          requests:
            memory: "32Mi"
            cpu: "10m"
          limits:
            memory: "64Mi"
            cpu: "100m"
      - name: migrate
        image: europe-west1-docker.pkg.dev/u2i-tenant-webapp-nonprod/webapp-images/webapp:${STAGE}-${COMMIT_SHA}
        command: ["node", "migrate.js"]
        env:
        - name: PROJECT_ID
          value: "${PROJECT_ID}"
        - name: BOUNDARY
          value: "${BOUNDARY}"
        - name: STAGE
          value: "${STAGE}"
        - name: ALLOYDB_AUTH_PROXY
          value: "true"
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
      volumes:
      - name: shared-data
        emptyDir: {}