# Non-production ingress configuration patches
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../k8s-manifests/ingress.yaml

patches:
  - target:
      kind: Ingress
      name: webapp-ingress
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: dev.webapp.u2i.dev
      - op: replace
        path: /metadata/annotations/external-dns.alpha.kubernetes.io~1hostname
        value: "dev.webapp.u2i.dev"
  - target:
      kind: ManagedCertificate
      name: webapp-ssl-cert
    patch: |-
      - op: replace
        path: /spec/domains/0
        value: dev.webapp.u2i.dev