# Production Environment Configuration
# ISO 27001/SOC 2/GDPR Compliant Settings

metadata:
  environment: production
  region: europe-west1
  compliance:
    iso27001: enforced
    soc2_type2: enforced
    gdpr: enforced
  data_residency: eu

application:
  name: webapp-team
  namespace: webapp-team
  replicas: 3  # Higher replica count for HA
  
  image:
    repository: europe-west1-docker.pkg.dev/u2i-tenant-webapp/webapp-images/webapp
    tag: latest  # Will be overridden by CI/CD with specific version
    
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

  environment_variables:
    PORT: "8080"
    ENVIRONMENT: "production"
    REGION: "europe-west1"
    COMPLIANCE_MODE: "gdpr"
    LOG_LEVEL: "info"  # Less verbose logging in production
    
  probes:
    liveness:
      path: /health
      port: 8080
      initial_delay: 30
      period: 10
      timeout: 5
      failure_threshold: 3
    readiness:
      path: /ready
      port: 8080
      initial_delay: 5
      period: 5
      timeout: 3
      failure_threshold: 3

security:
  # Strict security for production
  pod_security_standard: restricted
  run_as_non_root: true
  run_as_user: 1000
  read_only_root_filesystem: true  # Strict read-only for production
  allow_privilege_escalation: false
  
  network_policy:
    enabled: true
    egress:
      - external_apis: true      # Allow necessary external APIs only
      - internet: false          # Restrict general internet access
      - allowed_domains:         # Explicitly allowed domains
          - "*.googleapis.com"
          - "*.gstatic.com"
    
  binary_authorization:
    enabled: true
    require_attestations:
      - security-scan
      - compliance-approval
      
infrastructure:
  resource_quota:
    requests:
      cpu: "4"
      memory: "8Gi"
    limits:
      cpu: "8"
      memory: "16Gi"
    pods: "20"
    services: "10"
    
  storage:
    persistent_volumes: "5"
    storage_class: "ssd"  # Faster storage for production
    
  autoscaling:
    enabled: true
    min_replicas: 3
    max_replicas: 10
    target_cpu_utilization: 70
    target_memory_utilization: 70

monitoring:
  metrics_enabled: true
  logging_level: "info"
  traces_enabled: true
  
  alerts:
    cpu_threshold: 70
    memory_threshold: 70
    error_rate_threshold: 1  # Strict error threshold
    response_time_threshold: 500  # 500ms max response time
    
  sla:
    availability: 99.9
    response_time_p95: 300  # 300ms 95th percentile
    
compliance:
  audit_logging: enforced
  data_encryption: enforced
  backup_retention_days: 2555  # 7 years for SOC 2 compliance
  
  change_control:
    approval_required: true
    security_review: required
    rollback_plan: required
    
  monitoring:
    real_time_alerts: enabled
    compliance_dashboard: enabled
    audit_reports: automated
    
  labels:
    environment: "production"
    data-classification: "confidential"
    compliance-framework: "iso27001-soc2-gdpr"
    gdpr-compliant: "true"
    cost-center: "webapp-team"
    sla-tier: "gold"
    
disaster_recovery:
  backup_frequency: "daily"
  backup_retention: "7-years"
  rto: "4-hours"  # Recovery Time Objective
  rpo: "1-hour"   # Recovery Point Objective
  
performance:
  caching:
    enabled: true
    ttl: "5m"
  connection_pooling:
    enabled: true
    max_connections: 100