# Namespace for preview deployments
apiVersion: v1
kind: Namespace
metadata:
  name: ${NAMESPACE} # from-param: ${NAMESPACE}
  labels:
    app: webapp
    stage: ${STAGE} # from-param: ${STAGE}
    boundary: ${BOUNDARY} # from-param: ${BOUNDARY}
    tier: ${TIER} # from-param: ${TIER}
    environment: ${ENV} # from-param: ${ENV}