# Namespace for webapp deployments in prod
apiVersion: v1
kind: Namespace
metadata:
  name: ${NAMESPACE} # from-param: ${NAMESPACE}
  annotations:
    cnrm.cloud.google.com/project-id: u2i-tenant-webapp-prod
  labels:
    app: webapp
    stage: ${STAGE} # from-param: ${STAGE}
    boundary: ${BOUNDARY} # from-param: ${BOUNDARY}
    tier: ${TIER} # from-param: ${TIER}
    environment: ${ENV} # from-param: ${ENV}