# Cloud Deploy Configuration for Dev Environment
# Single stage deployment with kubectl for proper sequencing

apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: webapp-dev-pipeline
  labels:
    compliance: iso27001-soc2-gdpr
    team: webapp-team
    purpose: development
description: "Dev deployment pipeline with single stage"

serialPipeline:
  stages:
  - targetId: dev-gke
    profiles: ["dev"]
    strategy:
      standard:
        verify: false
    deployParameters:
      - values:
          NAMESPACE: "webapp-dev"
          ENV: "dev"
          API_URL: "https://api-dev.webapp.u2i.dev"
          STAGE: "dev"
          BOUNDARY: "nonprod"
          TIER: "standard"
          NAME_PREFIX: "dev-"
          DOMAIN: "dev.webapp.u2i.dev"
          ROUTE_NAME: "webapp-dev-route"
          SERVICE_NAME: "dev-webapp-service"
          CERT_NAME: "webapp-dev-cert"
          CERT_ENTRY_NAME: "webapp-dev-entry"
          CERT_DESCRIPTION: "Certificate for dev.webapp.u2i.dev"
          PROJECT_ID: "u2i-tenant-webapp-nonprod"
          PDB_MIN_AVAILABLE: "1"
          APP_NAME: "webapp"

---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: dev-gke
  labels:
    compliance: iso27001-soc2-gdpr
    environment: dev
    data-residency: eu
description: "Dev deployment target"

gke:
  cluster: projects/u2i-tenant-webapp-nonprod/locations/europe-west1/clusters/webapp-cluster
  
executionConfigs:
- usages: [RENDER, DEPLOY]
  serviceAccount: cloud-deploy-sa@u2i-tenant-webapp-nonprod.iam.gserviceaccount.com
  artifactStorage: gs://u2i-tenant-webapp-nonprod-deploy-artifacts