# Cloud Deploy Configuration for Preview Deployments
# Single stage with kubectl preDeploy hook for proper sequencing

apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: webapp-preview-pipeline
  labels:
    compliance: iso27001-soc2-gdpr
    team: webapp-team
    purpose: preview
description: "Preview deployment with Config Connector certificate provisioning"

serialPipeline:
  stages:
  - targetId: preview-gke
    profiles: ["preview-all"]
    strategy:
      standard:
        verify: false
    deployParameters:
      - values:
          APP_NAME: "webapp"

---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: preview-gke
  labels:
    compliance: iso27001-soc2-gdpr
    environment: preview
    data-residency: eu
description: "Preview deployment target"

gke:
  cluster: projects/u2i-tenant-webapp-nonprod/locations/europe-west1/clusters/webapp-cluster
  
executionConfigs:
- usages: [RENDER, DEPLOY, PREDEPLOY]
  serviceAccount: cloud-deploy-sa@u2i-tenant-webapp-nonprod.iam.gserviceaccount.com
  artifactStorage: gs://u2i-tenant-webapp-nonprod-deploy-artifacts