apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Prod profile - production-grade resources and high availability

patches:
- target:
    kind: Deployment
    labelSelector: app=webapp
  patch: |-
    - op: replace
      path: /spec/replicas
      value: 3
    - op: replace
      path: /spec/template/spec/containers/0/resources
      value:
        requests:
          memory: "512Mi"
          cpu: "500m"
        limits:
          memory: "1Gi"
          cpu: "1000m"
    - op: add
      path: /spec/template/spec/affinity
      value:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - webapp
              topologyKey: kubernetes.io/hostname

resources:
- ../../base
- horizontal-pod-autoscaler.yaml

configMapGenerator:
- name: webapp-profile-config
  literals:
    - PROFILE=prod
    - LOG_LEVEL=info
    - GRACEFUL_SHUTDOWN_TIMEOUT=30s
    - ENABLE_PROFILING=false
    - ENABLE_METRICS=true