apiVersion: batch/v1
kind: Job
metadata:
  name: webapp-migrate-${SHORT_SHA} # Unique name per deployment
  namespace: ${NAMESPACE}
  labels:
    app: webapp
    component: migration
    version: ${SHORT_SHA}
spec:
  ttlSecondsAfterFinished: 3600 # Clean up after 1 hour
  backoffLimit: 3
  template:
    metadata:
      labels:
        app: webapp
        component: migration
    spec:
      serviceAccountName: webapp
      automountServiceAccountToken: true
      restartPolicy: Never
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 2000
      containers:
      # AlloyDB Auth Proxy sidecar with IAM authentication
      - name: alloydb-auth-proxy
        image: gcr.io/alloydb-connectors/alloydb-auth-proxy:latest
        args:
          - "--port=5432"
          - "--instances=${ALLOYDB_INSTANCE_URI}=tcp:5432"
          - "--max-connections=10"
          - "--private-ip"
          - "--auto-iam-authn" # Enable automatic IAM authentication
        securityContext:
          runAsNonRoot: true
          runAsUser: 2000
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        resources:
          requests:
            memory: "32Mi"
            cpu: "10m"
          limits:
            memory: "64Mi"
            cpu: "100m"
      - name: migrate
        image: europe-west1-docker.pkg.dev/u2i-tenant-webapp-prod/webapp-images/webapp # Will use latest built image
        command: ["node", "migrate.js"]
        env:
        - name: PROJECT_ID
          value: "${PROJECT_ID}"
        - name: BOUNDARY
          value: "${BOUNDARY}"
        - name: STAGE
          value: "${STAGE}"
        - name: ALLOYDB_AUTH_PROXY
          value: "true"
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"