# Autoneg Controller Deployment
# This controller automatically manages NEG attachments to backend services
# Note: The service account is created by Terraform

# Namespace for Autoneg controller
apiVersion: v1
kind: Namespace
metadata:
  name: autoneg-system
---
# ServiceAccount for Autoneg controller with Workload Identity annotation
apiVersion: v1
kind: ServiceAccount
metadata:
  name: autoneg-controller-manager
  namespace: autoneg-system
  annotations:
    # This annotation will be added by Terraform output
    iam.gke.io/gcp-service-account: autoneg-controller@u2i-tenant-webapp.iam.gserviceaccount.com
---
# ClusterRole for Autoneg controller
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: autoneg-manager-role
rules:
- apiGroups:
  - ""
  resources:
  - services
  - endpoints
  - events
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
- apiGroups:
  - ""
  resources:
  - services/status
  verbs:
  - get
  - update
  - patch
---
# ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: autoneg-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: autoneg-manager-role
subjects:
- kind: ServiceAccount
  name: autoneg-controller-manager
  namespace: autoneg-system
---
# Deployment for Autoneg controller
apiVersion: apps/v1
kind: Deployment
metadata:
  name: autoneg-controller-manager
  namespace: autoneg-system
  labels:
    app: autoneg-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autoneg-controller
  template:
    metadata:
      labels:
        app: autoneg-controller
    spec:
      serviceAccountName: autoneg-controller-manager
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
      containers:
      - name: controller
        image: gcr.io/google-containers/autoneg-controller:v0.9.9
        args:
        - --project-id=u2i-tenant-webapp
        - --backend-project-id=u2i-gke-nonprod
        - --v=2
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 50m
            memory: 64Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true