apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: webapp-team

resources:
- ../../base
- ../../profiles/dev  # Use dev profile for resources
- config-connector-resources.yaml

configMapGenerator:
- name: webapp-env-config
  literals:
    - ENVIRONMENT=dev
    - API_URL=https://api-dev.webapp.u2i.dev