apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Dev environment with Gateway API
# Single stage deployment

resources:
# Use base kustomization which includes all base resources
- ../../base

# Use shared component for PDB configuration
components:
- ../../components/pdb-minAvailable-1

# Common labels for all resources
# Environment-specific labels only (core labels come from base)
labels:
- pairs:
    environment: dev
  includeSelectors: false