apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: webapp-team

resources:
- ../../base
- ../../profiles/prod  # Use prod profile for resources
- config-connector-resources.yaml

configMapGenerator:
- name: webapp-env-config
  literals:
    - BOUNDARY=production
    - API_URL=https://api.webapp.u2i.com