apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Single overlay for preview deployments
# Combines all resources needed for preview environment

resources:
# Use base kustomization which includes all base resources
- ../../base

# Common labels for all resources - Skaffold will merge with skaffold.dev/run-id
commonLabels:
  app.kubernetes.io/component: webapp