apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webapp-ingress
  namespace: webapp-team
  labels:
    app: webapp
    tenant: webapp-team
    compliance: iso27001-soc2-gdpr
  annotations:
    # Dynamic IP allocation - no static IP specified
    networking.gke.io/managed-certificates: "webapp-ssl-cert"
    kubernetes.io/ingress.allow-http: "true"  # Allow HTTP during cert provisioning
    # For external-dns if installed
    external-dns.alpha.kubernetes.io/hostname: "${INGRESS_HOSTS}"
spec:
  ingressClassName: "gce"
  rules:
  - host: ${INGRESS_HOST}  # Will be replaced by kustomize per environment
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: webapp-service
            port:
              number: 80
---
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: webapp-ssl-cert
  namespace: webapp-team
  labels:
    app: webapp
    tenant: webapp-team
    compliance: iso27001-soc2-gdpr
spec:
  domains:
  - ${INGRESS_HOST}  # Will be replaced by kustomize per environment