apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Ultra-lightweight preview - no ingress, no LB
# Access via kubectl port-forward or LoadBalancer service
namespace: webapp-team

resources:
- ../../base

# Remove the ingress entirely
patches:
- target:
    kind: Service
    name: webapp-service
  patch: |-
    - op: replace
      path: /spec/type
      value: LoadBalancer
    - op: add
      path: /metadata/annotations
      value:
        # Use container-native load balancing (no instance groups)
        cloud.google.com/neg: '{"ingress": false}'
        # Use the cheapest LB option
        networking.gke.io/load-balancer-type: "External"

# Labels for preview environments
labels:
- pairs:
    team: webapp-team
    tier: preview
  includeSelectors: false