apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: webapp-qa-deployment
build:
  artifacts:
  - image: europe-west1-docker.pkg.dev/u2i-tenant-webapp/webapp-images/webapp
    docker:
      dockerfile: Dockerfile
  tagPolicy:
    gitCommit:
      variant: Tags
  googleCloudBuild:
    projectId: u2i-tenant-webapp
    region: europe-west1
manifests:
  kustomize:
    paths:
    - k8s/overlays/qa
profiles:
- name: qa
  manifests:
    kustomize:
      paths:
      - k8s/overlays/qa
# Add dev profile for Cloud Deploy compatibility
- name: dev
  manifests:
    kustomize:
      paths:
      - k8s/overlays/qa