apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# QA environment with Gateway API
# Single stage deployment

resources:
# Use base kustomization which includes all base resources
- ../../base

# Common labels for all resources
commonLabels:
  app.kubernetes.io/component: webapp
  environment: qa
  compliance: iso27001-soc2-gdpr