apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp # from-param: ${NAME_PREFIX}${APP_NAME}
  namespace: ${NAMESPACE} # from-param: ${NAMESPACE}
  labels:
    app: webapp # from-param: ${APP_NAME}
    stage: ${STAGE} # from-param: ${STAGE}
    boundary: ${BOUNDARY} # from-param: ${BOUNDARY}
    tier: ${TIER} # from-param: ${TIER}
    environment: ${ENV} # from-param: ${ENV}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp # from-param: ${APP_NAME}
  template:
    metadata:
      labels:
        app: webapp # from-param: ${APP_NAME}
        tenant: webapp-team # from-param: ${APP_NAME}-team
        compliance: iso27001-soc2-gdpr
        data-residency: eu
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
    spec:
      serviceAccountName: webapp # from-param: ${APP_NAME}
      automountServiceAccountToken: true # Required for workload identity
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 3000
        fsGroup: 2000
        seccompProfile:
          type: RuntimeDefault
      initContainers:
      # AlloyDB Auth Proxy sidecar (runs as init container with restartPolicy: Always)
      - name: alloydb-auth-proxy
        image: gcr.io/alloydb-connectors/alloydb-auth-proxy:latest
        restartPolicy: Always  # This makes it a sidecar
        args:
        - "projects/u2i-tenant-webapp-nonprod/locations/europe-west1/clusters/webapp-nonprod-alloydb/instances/webapp-nonprod-alloydb-primary"
        - "--port=5432"
        - "--max-connections=50"
        - "--auto-iam-authn"
        startupProbe:
          tcpSocket:
            port: 5432
          initialDelaySeconds: 1
          periodSeconds: 1
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 30
        securityContext:
          runAsNonRoot: true
          runAsUser: 2000
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        resources:
          requests:
            memory: "32Mi"
            cpu: "10m"
          limits:
            memory: "64Mi"
            cpu: "100m"
      containers:
      - name: webapp # from-param: ${APP_NAME}
        image: europe-west1-docker.pkg.dev/u2i-tenant-webapp-nonprod/webapp-images/webapp
        ports:
        - containerPort: 8080
          name: http
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          runAsNonRoot: true
          runAsUser: 1000
          capabilities:
            drop:
            - ALL
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        env:
        - name: PORT
          value: "8080"
        - name: BOUNDARY
          value: "${BOUNDARY}" # from-param: ${BOUNDARY}
        - name: STAGE
          value: "${STAGE}" # from-param: ${STAGE}
        - name: REGION
          value: "europe-west1"
        - name: COMPLIANCE_MODE
          value: "gdpr"
        - name: PROJECT_ID
          value: "u2i-tenant-webapp-nonprod" # GCP project for Secret Manager access
        - name: ALLOYDB_AUTH_PROXY
          value: "true" # Using AlloyDB Auth Proxy sidecar
        # Database configuration from ConfigMap (if exists)
        envFrom:
        - configMapRef:
            name: webapp-neon-db-config # from-param: ${APP_NAME}-neon-db-config
            optional: true
        # Note: Database credentials are now fetched directly from Secret Manager
        # The app uses PROJECT_ID and STAGE to construct the secret name
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts:
        - name: tmp
          mountPath: /tmp
      volumes:
      - name: tmp
        emptyDir: {}