apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# App-specific resources
resources:
- deployment.yml
- service.yml
- httproute.yml
- external-secret.yml
- migration-job.yml
# Note: namespace.yml is handled separately by Cloud Deploy

# Reusable components for common patterns
components:
- ../../components/networking/gke-network-policy
- ../../components/security/workload-identity
- ../../components/observability/autoscaling

# Use labels instead of commonLabels to avoid modifying selectors
# commonLabels would add these to selectors which breaks the service
labels:
- pairs:
    app.kubernetes.io/component: webapp
    tenant: webapp-team
    compliance: iso27001-soc2-gdpr
    data-residency: eu
  includeSelectors: false
# Keep app label in deployment/pod templates only, not in selectors