apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: webapp-pdb # from-param: ${APP_NAME}-pdb
  namespace: ${NAMESPACE} # from-param: ${NAMESPACE}
spec:
  minAvailable: ${PDB_MIN_AVAILABLE} # from-param: ${PDB_MIN_AVAILABLE}
  selector:
    matchLabels:
      app: webapp # from-param: ${APP_NAME}
  # Allow disruption during maintenance windows
  unhealthyPodEvictionPolicy: AlwaysAllow
  # Note: PDB selector only needs to match a subset of pod labels