name: Deploy to QA/Prod

on:
  push:
    tags:
      - 'v*'

env:
  GCP_PROJECT: u2i-tenant-webapp-nonprod
  GCP_REGION: europe-west1
  PIPELINE: webapp-qa-prod-pipeline

jobs:
  deploy-qa:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
    - uses: actions/checkout@v4
    
    - uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
        service_account: ${{ secrets.WIF_SERVICE_ACCOUNT }}
    
    - uses: google-github-actions/setup-gcloud@v2
      with:
        install_components: 'gke-gcloud-auth-plugin'
    
    - name: Deploy to QA
      run: |
        # Convert tag name to valid release ID (replace dots with hyphens)
        RELEASE_ID=$(echo "${GITHUB_REF_NAME}" | sed 's/\./-/g')
        gcloud deploy releases create "${RELEASE_ID}" \
          --delivery-pipeline=webapp-qa-prod-pipeline \
          --region=${{ env.GCP_REGION }} \
          --project=${{ env.GCP_PROJECT }} \
          --skaffold-file=skaffold-single-stage.yaml \
          --to-target=qa-gke \
          --deploy-parameters="NAMESPACE=webapp-qa,ENV=qa,API_URL=https://api-qa.webapp.u2i.dev,STAGE=qa,BOUNDARY=nonprod,TIER=standard,DOMAIN=qa.webapp.u2i.dev,ROUTE_NAME=webapp-qa-route,SERVICE_NAME=webapp-service,CERT_NAME=webapp-qa-cert,CERT_ENTRY_NAME=webapp-qa-entry,CERT_DESCRIPTION=Certificate for qa.webapp.u2i.dev"
    
    - name: Create Production Promotion Issue
      uses: actions/github-script@v7
      with:
        script: |
          const issue = await github.rest.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: `Deploy ${context.ref.replace('refs/tags/', '')} to Production`,
            body: `## Production Deployment Request
            
            **Version**: ${context.ref.replace('refs/tags/', '')}
            **QA Deployment**: ✅ Completed
            
            ### Checklist
            - [ ] QA testing completed
            - [ ] Security scan passed
            - [ ] Performance benchmarks met
            - [ ] Release notes prepared
            
            ### Approval
            Please approve this deployment by:
            1. Checking all items in the checklist
            2. Running the production promotion workflow
            
            /cc @webapp-team/prod-approvers`,
            labels: ['deployment', 'production', 'needs-approval']
          });
          
          console.log(`Created issue #${issue.data.number}`);

  notify:
    needs: deploy-qa
    runs-on: ubuntu-latest
    steps:
    - name: Notify Slack
      run: |
        echo "QA deployment completed for ${{ github.ref_name }}"
        # Add actual Slack notification here