name: Deploy to Dev

on:
  push:
    branches:
      - main

env:
  GCP_PROJECT: u2i-tenant-webapp-nonprod
  GCP_REGION: europe-west1
  PIPELINE: webapp-dev-pipeline

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
    - uses: actions/checkout@v4
    
    - uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: 'projects/495368984538/locations/global/workloadIdentityPools/webapp-github-wif/providers/github'
        service_account: 'cloud-deploy-sa@u2i-tenant-webapp-nonprod.iam.gserviceaccount.com'
    
    - uses: google-github-actions/setup-gcloud@v2
      with:
        install_components: 'gke-gcloud-auth-plugin'
    
    - name: Deploy to Dev
      run: |
        gcloud deploy releases create "dev-${GITHUB_SHA:0:7}" \
          --delivery-pipeline=webapp-dev-pipeline \
          --region=${{ env.GCP_REGION }} \
          --project=${{ env.GCP_PROJECT }} \
          --skaffold-file=skaffold-single-stage.yaml \
          --to-target=dev-gke \
          --deploy-parameters="NAMESPACE=webapp-dev,ENV=dev,API_URL=https://api-dev.webapp.u2i.dev,STAGE=dev,BOUNDARY=nonprod,TIER=standard,NAME_PREFIX=dev-,DOMAIN=dev.webapp.u2i.dev,ROUTE_NAME=webapp-dev-route,SERVICE_NAME=webapp-service,CERT_NAME=webapp-dev-cert,CERT_ENTRY_NAME=webapp-dev-entry,CERT_DESCRIPTION=Certificate for dev.webapp.u2i.dev"