# Certificate resources for QA environment
---
# Google-managed certificate for the QA domain
apiVersion: certificatemanager.cnrm.cloud.google.com/v1beta1
kind: CertificateManagerCertificate
metadata:
  name: webapp-qa-cert # from-param: ${CERT_NAME}
  namespace: ${NAMESPACE} # from-param: ${NAMESPACE}
  annotations:
    cnrm.cloud.google.com/project-id: u2i-tenant-webapp-nonprod
spec:
  projectRef:
    external: u2i-tenant-webapp-nonprod
  location: global
  description: Certificate for qa.webapp.u2i.dev # from-param: ${CERT_DESCRIPTION}
  managed:
    domains:
    - qa.webapp.u2i.dev # from-param: ${DOMAIN}

---
# Certificate map entry to associate certificate with the map
apiVersion: certificatemanager.cnrm.cloud.google.com/v1beta1
kind: CertificateManagerCertificateMapEntry  
metadata:
  name: webapp-qa-entry # from-param: ${CERT_ENTRY_NAME}
  namespace: ${NAMESPACE} # from-param: ${NAMESPACE}
  annotations:
    cnrm.cloud.google.com/project-id: u2i-tenant-webapp-nonprod
spec:
  projectRef:
    external: u2i-tenant-webapp-nonprod
  mapRef:
    name: webapp-cert-map
    namespace: infra-gw
  certificatesRefs:
  - name: webapp-qa-cert # from-param: ${CERT_NAME}
  hostname: qa.webapp.u2i.dev # from-param: ${DOMAIN}