# Autoscaling Component
# Configures Horizontal Pod Autoscaler and Pod Disruption Budget for automatic scaling and availability
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - horizontal-pod-autoscaler.yml
  - pod-disruption-budget.yml